### ISSUE TITLE
Add about Hacktoberfest md file

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#10]
Description:

We need a new markdown file named `ABOUT_HACKTOBERFEST` and this file should have below mentioned points

1. Welcome quote
2. Hacktoberfest-2022 banner
3. what is hacktoberfest
5. swags 
6. where to find repos

PR Requirement:

- Please check the above requirements are met
- Always create new branch on forked repo from master to avoid and error while merging the fix
- Please **Star this repo while forking** as that would increase this repo's visibility

Cheers 🎉

**Comment by Sayan2908** [comment]
@jsvigneshkanna Can I work on it?

**Comment by jsvigneshkanna** [comment]
Hi @Sayan2908 
Yeah pleade go one, take time to check whether checklists are met and please don't forget to star this cool project

Cheers mate 🍻

**Comment by jsvigneshkanna** [comment]
Thanks @Sayan2908 , for contribution, check for other issues too.
