### ISSUE TITLE
[Feature]: Add loader to pages

### ISSUE THREAD

**Issue by kuldeepmangla** [jsvigneshkanna/tailwind_ui_components#103]
### Feature Title

Add loader

### Description

Whenever we switch between the pages it takes time so I want to add loader in it

### Motivation

Whenever we switch between the pages it takes time so I want to add loader in it

### Issue Type

Frontend

### Are you taking this fetaure implementaion

yes

**Comment by kuldeepmangla** [comment]
hey @jsvigneshkanna Can I add loader ?

**Comment by jsvigneshkanna** [comment]
Sure @kuldeepmangla , great idea
You can work on this issue

**Comment by jsvigneshkanna** [comment]
closing as done @kuldeepmangla ,

Check other issues like https://github.com/jsvigneshkanna/tailwind_ui_components/issues/40 https://github.com/jsvigneshkanna/tailwind_ui_components/issues/53 https://github.com/jsvigneshkanna/tailwind_ui_components/issues/54
