### ISSUE TITLE
[FEATURE]: Basic feature card in tailwindcss

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#109]
### Description

**Need to create code for Basic feature card  as per below image.**

- The final code should be placed under path `tailwind_components/feature_cards` with file name as `basic_card.jsx`
- The file as to be imported to `tailwind_components/feature_cards/collection.js` file as per example and added to the `featureCardColletion` list
- Post these process, go to components tab (components/feature_cards) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196936856-20a1b62f-f31e-44b3-9e86-0a806761997d.png)

### Are you taking this fetaure implementaion

no

**Comment by iamkennis** [comment]
@jsvigneshkanna   assign me

**Comment by jsvigneshkanna** [comment]
@iamkennis  Sure, also check other issues

**Comment by jsvigneshkanna** [comment]
Hi @iamkennis , let me know if help needed

**Comment by iamkennis** [comment]
@jsvigneshkanna  sorry i was cut up with other things, I will make some PR soon

**Comment by jsvigneshkanna** [comment]
@iamkennis take your time
