### ISSUE TITLE
[FEATURE]: Learn More card in tailwindcss

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#111]
### Description

**Need to create code for Learn More feature card  as per below image.**

- The final code should be placed under path `tailwind_components/feature_cards` with file name as `learn_more_card.jsx`
- The file as to be imported to `tailwind_components/feature_cards/collection.js` file as per example and added to the `featureCardColletion` list
- Post these process, go to components tab (components/feature_cards) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196937505-5a906fbc-3714-4332-af87-96fed843188c.png)

### Are you taking this fetaure implementaion

no

**Comment by tanisha-tech360** [comment]
Hey can you please assign me this issue?

**Comment by jsvigneshkanna** [comment]
Hi @tanisha-tech360 ,
Sure you can work on this issue, also check for other card components too

**Comment by jsvigneshkanna** [comment]
Hi @tanisha-tech360 ,
let me know if any help needed

**Comment by jsvigneshkanna** [comment]
@tanisha-tech360,
can you raise PR which you showed in discord
