### ISSUE TITLE
[FEATURE]: product card in tailwindcss

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#112]
### Description

**Need to create code for product card feature card  as per below image.**

- The final code should be placed under path `tailwind_components/feature_cards` with file name as `product_card1.jsx`
- The file as to be imported to `tailwind_components/feature_cards/collection.js` file as per example and added to the `featureCardColletion` list
- Post these process, go to components tab (components/feature_cards) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196937838-f2f73ddb-a656-47c6-ac3d-c52a3174182b.png)

### Are you taking this fetaure implementaion

no

**Comment by Anuran12** [comment]
@jsvigneshkanna like to work on this

**Comment by jsvigneshkanna** [comment]
@Anuran12 ,
Please make sure, the final result is same as screenshot (us image with transparency)
