### ISSUE TITLE
[FEATURE]: Brand card in tailwindcss

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#113]
### Description

**Need to create code for Brand card feature card  as per below image.**

- The final code should be placed under path `tailwind_components/feature_cards` with file name as `brand_card.jsx`
- The file as to be imported to `tailwind_components/feature_cards/collection.js` file as per example and added to the `featureCardColletion` list
- Post these process, go to components tab (components/feature_cards) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196938252-97a4dc1f-0e88-4425-9b70-933f2a337bee.png)

### Are you taking this fetaure implementaion

no

**Comment by Anuran12** [comment]
@jsvigneshkanna  like to work on this
