### ISSUE TITLE
[FEATURE]: Testimonial card with stars in tailwindCSS

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#115]
### Description

**Need to create code for Testimonial card with stars card as per below image.**

- The final code should be placed under path `tailwind_components/testimonial_cards` with file name as `photo_star_testimonial.jsx`
- The file as to be imported to `tailwind_components/testimonial_cards/collection.js` file as per example and added to the `testimonialCardsCollections` list
- For photo in card, you can add sample photo from internet
- Post these process, go to components tab (components/testimonial_card) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196954525-666d1d11-c75c-437f-a650-01013014e06d.png)

### Are you taking this fetaure implementaion

no

**Comment by Ankur2606** [comment]
Please assign me this task , I'll  reach back to you in the morning ist.

**Comment by Ankur2606** [comment]
I'll resolve all three issues and send pr by tonight . Sorry for the delay.

**Comment by jsvigneshkanna** [comment]
No problem @Ankur2606 
Make sure not to encounter plagiarism from any website, as we thrive to keep these components unique 

Let me know if any help needed
