### ISSUE TITLE
[FEATURE]: Links Testimonial card in tailwindCSS

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#116]
### Description

**Need to create code for Links Testimonial card as per below image.**

- The final code should be placed under path `tailwind_components/testimonial_cards` with file name as `social_link_testimonial.jsx`
- The file as to be imported to `tailwind_components/testimonial_cards/collection.js` file as per example and added to the `testimonialCardsCollections` list
- For photo in card, you can add sample photo from internet (or use your's)
- Post these process, go to components tab (components/testimonial_card) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196955271-b149c749-6b6c-4d8a-9dca-76de7e8ea2b0.png)

### Are you taking this fetaure implementaion

no

**Comment by Ankur2606** [comment]
Please assign me this task , I'll  reach back to you in the morning ist.

**Comment by jsvigneshkanna** [comment]
Great @Ankur2606 
please follow the folder structure and take reference for other PRs
