### ISSUE TITLE
[FEATURE]: Horizontal Testimonial card in tailwindCSS

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#117]
### Description

**Need to create code for Horizontal Testimonial card with stars card as per below image.**

- The final code should be placed under path `tailwind_components/testimonial_cards` with file name as `horizontal_testimonial.jsx`
- The file as to be imported to `tailwind_components/testimonial_cards/collection.js` file as per example and added to the `testimonialCardsCollections` list
- For photo in card, you can add sample photo from internet (or your's)
- Post these process, go to components tab (components/testimonial_card) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196955640-277d7e29-4aad-4f9b-9e17-13088d392824.png)

### Are you taking this fetaure implementaion

no

**Comment by jsvigneshkanna** [comment]
@Ankur2606 assigning to you, please dont forget to to raise PRs, as we are assinging 3 issues to your name

**Comment by jsvigneshkanna** [comment]
Hi @Ankur2606 ,

Just a reminder, please fix this issue :)

**Comment by Ankur2606** [comment]
## I'll get it done right away . Sorry for the delay.
