### ISSUE TITLE
[FEATURE]: Vertical testimonial card in tailwindCSS

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#118]
### Description

**Need to create code for Vertical Testimonial card with stars card as per below image.**

- The final code should be placed under path `tailwind_components/testimonial_cards` with file name as `vertical_testimonial.jsx`
- The file as to be imported to `tailwind_components/testimonial_cards/collection.js` file as per example and added to the `testimonialCardsCollections` list
- For photo in card, you can add sample photo from internet
- Post these process, go to components tab (components/testimonial_card) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196955915-bf14b497-d084-416e-b0dd-5217863ddbb6.png)

### Are you taking this fetaure implementaion

no

**Comment by Ankur2606** [comment]
Please assign me this task , I'll  reach back to you tomorrow at night time ist.

**Comment by jsvigneshkanna** [comment]
@Ankur2606 , we only assign 3 issues at a time

**Comment by jsvigneshkanna** [comment]
Sure @Ankur2606 
Please make sure the result is same as screenshot
