### ISSUE TITLE
Missing contributing guide

### ISSUE THREAD

**Issue by VirginieLemaire** [jsvigneshkanna/tailwind_ui_components#12]
Hi 😃 
I saw your message on Hacktoberfest discord. Thanks for sharing your project
In the README you ask to follow the contributing guide but there is no contributing guide 🙈. I can add one and link it on README file if you want ;)

**Comment by jsvigneshkanna** [comment]
Hi @VirginieLemaire ,

Good check ⚡
You can create one new CONTRIBUTING.md file and link the existing readme.
Please make sure to cover below points for contributing guide

1. First raise new issue (bug/ feature/ ...) and get assigned from maintainers
2. Git workflows to fork, create new branch, make changes, commit with good message, push them
3. Create PR with suitable and crisp title
4. follow the PR template without compromising anything
5. mention anyone of the reviewers (my name for now)
6. Star this repo (bit of self boosting 😉) to make this project cooler
