### ISSUE TITLE
Standard pricing card in tailwindCSS

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#124]
### Description

**Need to create code for Standard pricing card as per below image. **

- The final code should be placed under path `tailwind_components/pricing_cards` with file name as `standard_pricing.jsx`
- The file as to be imported to `tailwind_components/pricing_cards/collection.js` file as per example and added to the `pricingCardsCollections` list
- Post these process, go to components tab (components/pricing_cards) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196991028-34f26e03-31dd-48b0-b16b-01244aa327fc.png)

### Are you taking this fetaure implementaion

no

**Comment by uttampandit** [comment]
Hi @jsvigneshkanna I can work on this card component. If you can assign me?

**Comment by jsvigneshkanna** [comment]
Sure @uttampandit ,

Please also look for other pricing cards too, follow the folder structure taking reference from closed PRs

**Comment by uttampandit** [comment]
Sure

**Comment by uttampandit** [comment]
Hi @jsvigneshkanna does the card also includes green border?

**Comment by jsvigneshkanna** [comment]
@uttampandit , yes
