### ISSUE TITLE
Pricing card with button in tailwindCSS

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#125]
### Description

**Need to create code for Pricing card with button as per below image. **

- The final code should be placed under path `tailwind_components/pricing_cards` with file name as `pricing_with_button.jsx`
- The file as to be imported to `tailwind_components/pricing_cards/collection.js` file as per example and added to the `pricingCardsCollections` list
- Post these process, go to components tab (components/pricing_cards) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196991596-03ed91e5-ada6-49f1-b394-10d003994f74.png)

### Are you taking this fetaure implementaion

no

**Comment by jsvigneshkanna** [comment]
Sure @chibuike-19

Great involvement, appreciate that!

**Comment by chibuike-19** [comment]
Thanks @jsvigneshkanna!

**Comment by jsvigneshkanna** [comment]
Hi @chibuike-19 ,
Please let me know any help needed, as this issue was inactive for more than 2 days

**Comment by chibuike-19** [comment]
sorry, I've been having an issue with my system, would work on it tomorrow.

**Comment by jsvigneshkanna** [comment]
Sure @chibuike-19 no worries. just a reminder !

**Comment by MunavvarSinan** [comment]
Can you assign me the task if it is not done yet

**Comment by jsvigneshkanna** [comment]
@MunavvarSinan sure
Please make sure the code is not plagiarised, as it would cause copyright issue

**Comment by MunavvarSinan** [comment]
> @MunavvarSinan sure
> Please make sure the code is not plagiarised, as it would cause copyright issue

Okay

**Comment by MunavvarSinan** [comment]
what was the probelm?

**Comment by jsvigneshkanna** [comment]
@MunavvarSinan , can you raise new PR again
