### ISSUE TITLE
pricing card with ribbon in tailwindCSS

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#126]
### Description

**Need to create code for pricing card with ribbon as per below image. **

- The final code should be placed under path `tailwind_components/pricing_cards` with file name as `pricing_card_ribbon.jsx`
- The file as to be imported to `tailwind_components/pricing_cards/collection.js` file as per example and added to the `pricingCardsCollections` list
- Post these process, go to components tab (components/pricing_cards) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196991938-3d132e7c-9d50-47dd-909b-bb1908ad387e.png)

### Are you taking this fetaure implementaion

no

**Comment by Kabiirk** [comment]
Hi,

Can you please assign this to me ?

**Comment by jsvigneshkanna** [comment]
Great @Kabiirk 
Please make sure the design is same in result and have ribbon at top right
