### ISSUE TITLE
New FAQ page for website

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#133]
### Feature Title

FAQ page

### Description

Need to create new FAQ component which has below questions ( i will add the answers in PR) and display the component in homepage below banner

Question,

1. What is Tailwind Bootstrap
2. Who drives this website
3. What all components are there in this website
4. Can we play around with tailwindcss codes
5. Is there any pricing or subscription
6. How can we use these ui components and where can we find docs
7. I would like to contribute to this website, how can I proceed 

Please design this FAQ component as below screenshot with accordion

### Motivation

People who first arrive to new website have many question and this faq section is right place for them

### Issue Type

Frontend

### Screenshot of the feature if done ?

![image](https://user-images.githubusercontent.com/42484705/197010732-8daff4fa-f2a5-44cc-ab9f-f934643798b6.png)

### Are you taking this fetaure implementaion

No - up for grabs

**Comment by pratyushkr11** [comment]
Hi @jsvigneshkanna sir,  Please assign me this issue. I can help you with this.

**Comment by jsvigneshkanna** [comment]
@dishantzaveri 
Great welcome to our community

**Comment by jsvigneshkanna** [comment]
@pratyushkr11 , can you check issue #134

**Comment by jsvigneshkanna** [comment]
Hi @dishantzaveri 
Please let me know, if help needed as this issue was inactive for more than 2 days

**Comment by deepaksuthar40128** [comment]
Can you assign it to me?

**Comment by jsvigneshkanna** [comment]
Sure @deepaksuthar40128 
Make sure the FAQs question and answers are in seperate json and fetched in component
This is should be shown in accordian

**Comment by deepaksuthar40128** [comment]
Where i can add link of FAQ page, in navbar or footer?

**Comment by jsvigneshkanna** [comment]
Please create component for now, will think of where to display that @deepaksuthar40128

**Comment by jsvigneshkanna** [comment]
Thank you @deepaksuthar40128 , closing this issue as done
