### ISSUE TITLE
Simple contact form in tailwindCSS

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#137]
### Description

**Need to create code for Simple contact form as per below image. **

- The final code should be placed under path `tailwind_components/contact_forms` with file name as `standard_contact_form.jsx`
- The file as to be imported to `tailwind_components/contact_forms/collection.js` file as per example and added to the `contactFormsCollection` list
- Post these process, go to components tab (components/contact_forms) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/197019665-6fc3d435-440b-433a-b1cc-318f4eaed8cf.png)

### Are you taking this fetaure implementaion

no

**Comment by Anuran12** [comment]
@jsvigneshkanna  I would like to work on this

**Comment by jsvigneshkanna** [comment]
Sleepless night @Anuran12 ?
Assigning you this issue

**Comment by jsvigneshkanna** [comment]
Any updates @Anuran12 ?
