### ISSUE TITLE
Vertical contact form in tailwindCSS

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#139]
### Description

**Need to create code for Vertical contact form as per below image. **

- The final code should be placed under path `tailwind_components/contact_forms` with file name as `vertical_contact_form.jsx`
- The file as to be imported to `tailwind_components/contact_forms/collection.js` file as per example and added to the `contactFormsCollection` list
- Post these process, go to components tab (components/contact_forms) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/197020067-cac2b35d-ee44-4c64-92f3-4591ed1191b8.png)

### Are you taking this fetaure implementaion

no

**Comment by Anuran12** [comment]
@jsvigneshkanna  like to work on this

**Comment by jsvigneshkanna** [comment]
@Anuran12 please go on ⚡⚡

**Comment by jsvigneshkanna** [comment]
@Anuran12 please also check other issues which are assigned to you #112
