### ISSUE TITLE
Add contributors list to Readme

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#14]
Description:
As this repo is solely built by open source contributors, we need to thank them by highlighting them in Repo's Readme

Embed contributors list to readme with help of https://contrib.rocks/preview?repo=jsvigneshkanna%2Ftailwind_ui_components

PR Requirement:

- Please check the above requirements are met
- Always create new branch on forked repo from master to avoid and error while merging the fix
- Please Star this repo while forking as that would increase this repo's visibility

Cheers 🎉

**Comment by najeebkp** [comment]
hi @jsvigneshkanna please assign this to me

**Comment by jsvigneshkanna** [comment]
Hi @najeebkp ,

you can work on this issue, assigning your name
Please don's forget to star this repo to make it more cooler

Cheers 🍻
