### ISSUE TITLE
Subscription form in tailwindCSS

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#141]
### Description

**Need to create code for subscription form as per below image. **

- The final code should be placed under path `tailwind_components/contact_forms` with file name as `subscription_contact_form.jsx`
- The file as to be imported to `tailwind_components/contact_forms/collection.js` file as per example and added to the `contactFormsCollection` list
- Post these process, go to components tab (components/contact_forms) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/197020464-c1e07bdf-fd4e-47ef-b9eb-e51c951739a0.png)

### Are you taking this fetaure implementaion

no

**Comment by Myrfion** [comment]
Hi could u please assign this to me

**Comment by salvadorgonmo** [comment]
Hey @Myrfion let me know if you need a hand on this after you take it, would be happy to help.

**Comment by jsvigneshkanna** [comment]
Thank you @Myrfion for checking this repo, make sure design is followed and refer the other PRs for folder structure to reflect your code in webiste's codepen

**Comment by jsvigneshkanna** [comment]
@Myrfion / @salvadorgonmo any updates?

**Comment by SarveshPatil29** [comment]
Hey @jsvigneshkanna, I am interested in working on this issue. Can you please assign this issue to me?

**Comment by jsvigneshkanna** [comment]
Sure @SarveshPatil29

**Comment by SarveshPatil29** [comment]
Hey, @jsvigneshkanna shall I submit a new PR? I was just confirming because you haven't accepted the previous one.

**Comment by jsvigneshkanna** [comment]
@SarveshPatil29 , which one?

**Comment by SarveshPatil29** [comment]
> @SarveshPatil29 , which one?

The one in which i created privacy page

**Comment by jsvigneshkanna** [comment]
@SarveshPatil29 , merged your code, please check other issues 🍻
