### ISSUE TITLE
Need documentation of website (video)

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#142]
### Feature Title

Video on how to use the website

### Description

As the website - https://tailwindcsscomponents.vercel.app/ is growing very fast ⚡ than what we expect and as this website is entering `product hunt` in next week, we need a video recorded on how to use all the features of the website

The video can be of length 1-2 minutes and should have all the necessary information from the website, should cover all the pages from the website

We will attach the recorded video in homepage above footer with label having contributor name, and their social links

### Motivation

A nice video documentation is really needed for this website at this point

### Issue Type

Documentation

### Screenshot of the feature if done ?

Nill

### Are you taking this fetaure implementaion

no - up for grabs

**Comment by jsvigneshkanna** [comment]
Hi @itsagift ,
I Didnt thought of narration, but if you like to add that its appreciable
Are you taking this issue, can i assigne tou you?

**Comment by Swap-Nova** [comment]
I would like to work on this. Can you assign it to me?

**Comment by jsvigneshkanna** [comment]
@Swap-Nova , Sure
Will assign you too, Having 2 video documentations would be good

**Comment by Swap-Nova** [comment]
Thank you, I will work on it.

**Comment by Swap-Nova** [comment]
For the video do you need any narration or the working of the components itself?

**Comment by jsvigneshkanna** [comment]
@Swap-Nova ,
You can show each pages of the website, how many components are there in components page and how to use those components by playing in codepen playground

We dont need narration, simple soothing bg-music is enough

**Comment by Swap-Nova** [comment]
Okay sounds good. Thanks for the suggestions.

**Comment by jsvigneshkanna** [comment]
@Swap-Nova 
You can record video now as the website is revamped and styles are enhanced, please attach the recored video in public folder of this repo

**Comment by Swap-Nova** [comment]
Okay got it. Will work on it.

**Comment by Rosh-h** [comment]
hello @jsvigneshkanna  can you assign this is work to me.

**Comment by jsvigneshkanna** [comment]
@Rosh-h sure, you too can create a nice video with soothing background about our website

**Comment by jsvigneshkanna** [comment]
Hi @Rosh-h , @Swap-Nova , @itsagift  

Any updates. please let me know if any help needed

**Comment by Rosh-h** [comment]
If I create the video with loom in the voice narration will that be OK or documentation describing the features is also needed

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jsvigneshkanna** [comment]
@Rosh-h video alone is enough for now
