### ISSUE TITLE
[Bug]: update Readme with npm cmds

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#145]
### Bug Title

Update readme

### Description of BUG

The readme of the repo doesn't have npm commands that we use during development. Add those to the readme

Add the below points under the cotribution section

1. Checkout to the forked repo with a new branch for each PR/issue
2. `npm install` to install all js dependencies
3. `npm run dev` to start the local web server
4. Connect to localhost:3000 
5. Make changes to the codebase(nextJS and tailwind/plain CSS)
6. Commit changes and raise PR

### Reporduction URL of bug

Nill

### Bug Issue Type

Documentation

### Screenshot of the issue if in UI/ Document

Nill

### Are you taking this issue fix

Up for grabs

**Comment by Yordaniss** [comment]
Hello @jsvigneshkanna i could take this issue. Can you please assign this to me?

**Comment by jsvigneshkanna** [comment]
Hi @Yordaniss 
Welcome to 😎 community, also it would be appreciated if issue #142 is taken

**Comment by Yordaniss** [comment]
@jsvigneshkanna with video im not sure if i could do this. I let the opportunity for someone else to contribute to this project 😉 

For this issue i have already created a PR. Please review this and let me know if some changes are required.

**Comment by jsvigneshkanna** [comment]
@Yordaniss 
The PR looked perfect as per the requirement,  appreciate that

Please keep this repo in your watchlist to get notifed when new issues or feature request raised
