### ISSUE TITLE
navbar with social icons in tailwindCSS

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#156]
### Description

**Need to create code for navbar with social icons with Image as per below image. **

- The final code should be placed under path `tailwind_components/navbars` with file name as `navbar_social_icons.jsx`
- The file as to be imported to `tailwind_components/navbars/collection.js` file as per example and added to the `navbarCollections` list
- Post these process, go to components tab (components/navbars) in website and check whether the codepen is updated
- ### The navbar should be mobile responsive with hamburger menu (make it simple)

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/197176979-4817f023-49cf-437a-9b99-493e31554b21.png)

### Are you taking this fetaure implementaion

No, This is up for grabs

**Comment by uttampandit** [comment]
Hi @jsvigneshkanna again, I can work on this, can you please assign me?

**Comment by udaykahar** [comment]
Hi @jsvigneshkanna , I can work on this, can you please assign me?

**Comment by jsvigneshkanna** [comment]
Hi @uttampandit ,

Yeah sure, also check for other navbars if you can build those

**Comment by jsvigneshkanna** [comment]
@udaykahar ,

Can you please take issue #157

**Comment by jsvigneshkanna** [comment]
@udaykahar , comment over there #157 , will asign that to you

**Comment by udaykahar** [comment]
sure

**Comment by Viren0602** [comment]
Hello sir, can you assign this issue to me?

**Comment by jsvigneshkanna** [comment]
Welcome @Viren0602 
Please make sure the final result is same as screenshot and mobile responsive

**Comment by jsvigneshkanna** [comment]
No plagiarism to be followed

**Comment by mdb1710** [comment]
If this issue is still open I would love to take it on.

**Comment by jsvigneshkanna** [comment]
Sure @mdb1710 , please make sure this is not plagiarised from other sites
This should be mobile responsive

**Comment by Viren0602** [comment]
Sir I have raised a PR for #156 again. Now its not a plagiarised from other sites.
