### ISSUE TITLE
Simple logo navbar in tailwindCSS

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#157]
### Description

**Need to create code for Simple logo navbar with Image as per below image. **

- The final code should be placed under path `tailwind_components/navbars` with file name as `standard_logo_navbar.jsx`
- The file as to be imported to `tailwind_components/navbars/collection.js` file as per example and added to the `navbarCollections` list
- Post these process, go to components tab (components/navbars) in website and check whether the codepen is updated
- ### The navbar should be mobile responsive with hamburger menu (make it simple)

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/197177496-76c98cda-592d-4abc-8e19-14c29c613ffa.png)

### Are you taking this fetaure implementaion

No, This is up for grabs

**Comment by uttampandit** [comment]
Hi @jsvigneshkanna do we have to add any logo or just have to leave it blank?I can work on it as well.

**Comment by jsvigneshkanna** [comment]
@uttampandit ,
you can add your photo/ logo if in case you have and link that with your github on click 😎

**Comment by uttampandit** [comment]
Sure @jsvigneshkanna!

**Comment by kashish0604** [comment]
hey @jsvigneshkanna can u assign this issue to me i can work on it

**Comment by jsvigneshkanna** [comment]
Hi @kashish0604 ,
you can build this component too (use your own logo and color palete) and make sure to follow below folder structure (NOT THAT IN THE DESCRIPTION)

- The final code should be placed under path tailwind_components/navbars with file name as standard_logo_navbar.jsx
- The file as to be imported to tailwind_components/navbars/collection.js file as per example and added to the navbarCollections list
- Post these process, go to components tab (components/navbars) in website and check whether the codepen is updated

**Comment by udaykahar** [comment]
Can i also contribute in this?

**Comment by jsvigneshkanna** [comment]
Yes @udaykahar , make different file named logo_navbar3 under same folder mentioned with your own color palete and design

**Comment by udaykahar** [comment]
ok ready here 🙌

**Comment by Viren0602** [comment]
Hello sir , can you assign this issue to me?

**Comment by jsvigneshkanna** [comment]
Hi @Viren0602 , can you check other issues or raise new one for which you are building a component, because this is closed
