### ISSUE TITLE
Hovering navbar in tailwindCSS

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#158]
### Description

**Need to create code for Hovering navbar  as per below image. **

- The final code should be placed under path `tailwind_components/navbars` with file name as `hover_navbar.jsx`
- The file as to be imported to `tailwind_components/navbars/collection.js` file as per example and added to the `navbarCollections` list
- Post these process, go to components tab (components/navbars) in website and check whether the codepen is updated
- The color patterns and fornt are upto creativity
- ### The navbar should be mobile responsive with hamburger menu (make it simple)

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/197178299-a46b9de6-dcf9-48df-a799-4e1d1f6f5868.png)

### Are you taking this fetaure implementaion

No, This is up for grabs

**Comment by Iam-SilentEyes** [comment]
Can you assign me to this

**Comment by jsvigneshkanna** [comment]
Sure @Iam-SilentEyes ,

Also check for other issues too!

**Comment by jsvigneshkanna** [comment]
Hi @Iam-SilentEyes 
just a reminder :)

**Comment by Iam-SilentEyes** [comment]
Working on it

**Comment by jsvigneshkanna** [comment]
sure @Iam-SilentEyes

**Comment by Viren0602** [comment]
Hello sir, can you assign this issue to me?

**Comment by abirhasanohi** [comment]
@jsvigneshkanna can you please assign me on this issue?

**Comment by jsvigneshkanna** [comment]
@abirhasanohi sure, go ahead. Make sure no plagarism and star the repo to make it cooler

**Comment by jsvigneshkanna** [comment]
Sure @imohitkumar1610 , create filename with prefix new
Have your creativeness on building it

**Comment by AmanJain18** [comment]
Implement the require navbar with hamburger functioning
Assign this issue to me and let me know for any changes 🙂
