### ISSUE TITLE
Animated navbar component in tailwindCSS

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#159]
### Description

**Need to create code for Animated navbar component as per below image. **

- The final code should be placed under path `tailwind_components/navbars` with file name as `animated_navbar.jsx`
- The file as to be imported to `tailwind_components/navbars/collection.js` file as per example and added to the `navbarCollections` list
- Post these process, go to components tab (components/navbars) in website and check whether the codepen is updated
- Color palete and animation is upto creativity
- ### The navbar should be mobile responsive with hamburger menu (make it simple)

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/197178878-7b8c499d-fcc4-483b-9b6a-fe3ada333001.png)

### Are you taking this fetaure implementaion

No, This is up for grabs

**Comment by uttampandit** [comment]
Hi @jsvigneshkanna I can work on it, please assign me.

**Comment by jsvigneshkanna** [comment]
@uttampandit  yeah but, lets wait for sometime for other contributors too. If no pick up this in an hour, then I will assign this to you!

**Comment by streetcodec** [comment]
I am interested in this! Please assign! @jsvigneshkanna

**Comment by jsvigneshkanna** [comment]
welcome back @streetcodec 🤪
Also check for other navbar components too~
