### ISSUE TITLE
Center navbar with dropdown component in tailwindCSS

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#160]
### Description

**Need to create code for Center navbar with dropdown component as per below image. **

- The final code should be placed under path `tailwind_components/navbars` with file name as `center_dropdown_navbar.jsx`
- The file as to be imported to `tailwind_components/navbars/collection.js` file as per example and added to the `navbarCollections` list
- Post these process, go to components tab (components/navbars) in website and check whether the codepen is updated
- Color palete and design is upto creativity

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/197179783-24d69f97-b519-4192-8fa0-70ba1d00e673.png)

### Are you taking this fetaure implementaion

No, This is up for grabs

**Comment by uttampandit** [comment]
HI @jsvigneshkanna I can work on this too. Can you assign me please?

**Comment by jsvigneshkanna** [comment]
Sure @uttampandit , please make sure all 3 PRs are raised

**Comment by uttampandit** [comment]
Yeah I will

**Comment by jsvigneshkanna** [comment]
Hi @uttampandit ,
Just a reminder, you have 3 issues to be solved

**Comment by uttampandit** [comment]
Yes sure I am working on it

**Comment by jsvigneshkanna** [comment]
Sure @uttampandit
