### ISSUE TITLE
Standard mobile navbar component in tailwindCSS

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#161]
### Description

**Need to create code for Standard mobile navbar component as per below image. **

- The final code should be placed under path `tailwind_components/navbars` with file name as `standard_mobile_navbar.jsx`
- The file as to be imported to `tailwind_components/navbars/collection.js` file as per example and added to the `navbarCollections` list
- Post these process, go to components tab (components/navbars) in website and check whether the codepen is updated
- ### The navbar should be mobile responsive with hamburger menu (make it simple)

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/197180375-bfdf1a80-9149-4409-b561-480dd824c588.png)

### Are you taking this fetaure implementaion

No, This is up for grabs

**Comment by streetcodec** [comment]
Please assign this to me! @jsvigneshkanna

**Comment by jsvigneshkanna** [comment]
@streetcodec , can we wait for an hour so that other contributors can take this.
If no one picks in an hour, i will assign this to you

**Comment by rakicodes** [comment]
i would like to give it a try!
