### ISSUE TITLE
mobile navbar with Icons in tailwindCSS

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#162]
### Description

**Need to create code for mobile navbar with Icons as per below image. **

- The final code should be placed under path `tailwind_components/navbars` with file name as `mobile_nav_icons.jsx`
- The file as to be imported to `tailwind_components/navbars/collection.js` file as per example and added to the `navbarCollections` list
- Post these process, go to components tab (components/navbars) in website and check whether the codepen is updated
- ### The navbar should be mobile responsive with hamburger menu (make it simple)

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/197180762-1757e5e6-70db-4d7a-a63b-ad4ddc6ad0b0.png)

### Are you taking this fetaure implementaion

No, This is up for grabs

**Comment by streetcodec** [comment]
I am also interested here, please assign me this! @jsvigneshkanna I know to told me to only have atmost 2 assigned, but I want to do this too, please assign, if it's okay!

**Comment by jsvigneshkanna** [comment]
@streetcodec please make sure all 3 PRs are done 🙏
