### ISSUE TITLE
navbar with search function in tailwindCSS

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#164]
### Description

**Need to create code for navbar with search function as per below image. **

- The final code should be placed under path `tailwind_components/navbars` with file name as `search_navbar.jsx`
- The file as to be imported to `tailwind_components/navbars/collection.js` file as per example and added to the `navbarCollections` list
- Post these process, go to components tab (components/navbars) in website and check whether the codepen is updated
- ### The navbar should be mobile responsive with hamburger menu (make it simple)

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/197181523-68e7167d-2e81-4680-becf-12092aa01df9.png)

### Are you taking this fetaure implementaion

No, This is up for grabs

**Comment by Anuran12** [comment]
@jsvigneshkanna  i would like to work on this

**Comment by jsvigneshkanna** [comment]
Sure @Anuran12 ,
Please make sure all 3 PRs are raised 🙏
