### ISSUE TITLE
Colorful badges in tailwindCSS

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#165]
### Description

**Need to create code for Colorful badges as per below image. **

- The final code should be placed under path `tailwind_components/badges` with file name as `colorful_badgejsx`
- The file as to be imported to `tailwind_components/badges/collection.js` file as per example and added to the `badgeCollection` list
- Post these process, go to components tab (components/badges) in website and check whether the codepen is updated
- ### The badges should be in **different size** and displayed in **flex-column** to avoid overflow in codepen

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/197186766-e76bf4b7-d320-4420-8849-6e74faf4d4f8.png)

### Are you taking this fetaure implementaion

No, This is up for grabs

**Comment by alkhimch** [comment]
Can i handle this ? @jsvigneshkanna

**Comment by jsvigneshkanna** [comment]
Sure @alkhimch , you build this one
Please make the size and border radius different for each badge and follow the folder structure for codepen in website to work as expected

Let me know if any issues while building

**Comment by alkhimch** [comment]
Of course :)
