### ISSUE TITLE
Closing badge component in tailwindCSS

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#167]
### Description

**Need to create code for Closing badge component as per below image. **

- The final code should be placed under path `tailwind_components/badges` with file name as `close_badgejsx`
- The file as to be imported to `tailwind_components/badges/collection.js` file as per example and added to the `badgeCollection` list
- Post these process, go to components tab (components/badges) in website and check whether the codepen is updated
- ### The badges should close on cross-icon click

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/197187578-d3d9473c-0bce-4eb7-93d4-ade70cacfe6e.png)

### Are you taking this fetaure implementaion

No, This is up for grabs

**Comment by Muhammad-Shahid-Jamal** [comment]
Assign this to me as well.

**Comment by jsvigneshkanna** [comment]
Sure @Muhammad-Shahid-Jamal ,
Please follow the folder structure to make codepen work as expected, refer other PRs

**Comment by jsvigneshkanna** [comment]
Hi @Muhammad-Shahid-Jamal 
Let me know if any help needed

**Comment by uttampandit** [comment]
Hi @jsvigneshkanna can i work on this, please assign me.

**Comment by jsvigneshkanna** [comment]
Sure @uttampandit
