### ISSUE TITLE
Simple card with top badge in tailwindCSS

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#168]
### Description

**Need to create code for Simple card with top badge as per below image. **

- The final code should be placed under path `tailwind_components/badges` with file name as `card_badgejsx`
- The file as to be imported to `tailwind_components/badges/collection.js` file as per example and added to the `badgeCollection` list
- Post these process, go to components tab (components/badges) in website and check whether the codepen is updated
- ### The card can be as simple as just sample image and text (we are focussing on badge here)

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/197187958-2eacab2d-b43f-4332-b77a-99e0f776dbae.png)

### Are you taking this fetaure implementaion

No, This is up for grabs

**Comment by vaibhavg20comp** [comment]
Hey @jsvigneshkanna  I would love to work on  this.Please assign this to me

**Comment by jsvigneshkanna** [comment]
Welcome to our community @vaibhavg20comp 
Please make sure the folder structure is as per other PRs
Also check other issues which are open

**Comment by jsvigneshkanna** [comment]
Hi @vaibhavg20comp 

Please let me know, if help needed !

**Comment by SarveshPatil29** [comment]
Hey @jsvigneshkanna, I would like to work on this issue. Could you please assign this to me?

**Comment by jsvigneshkanna** [comment]
sure @SarveshPatil29
