### ISSUE TITLE
Chore issue template

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#17]
**Description:**
As this is a new repository, we need bug issue GitHub template. The template should be new tailwind component feature issue alone and should have below mentioned input fields

**Tailwind Component Feature template Requirement:**

1. Issue title should start with - [TCF]< title>
2. Description of the Tailwind component<Required>
5. Screenshot of the tailwind component <OPTIONAL>
6. Are you taking this tailwind component design <Required>

The template should be under `.github/ISSUE_TEMPLATE/TAILWIND-COMPONENT-FEATURE-REQUEST.yml`

Reference: https://github.com/stevemao/github-issue-templates

**PR Requirement:**
1. Please check the above requirements are met
2. Always create new branch on forked repo from master to avoid and error while merging the fix
3. Please Star this repo while forking as that would increase this repo's visibility

Cheers 🎉

**Comment by mpeiffer** [comment]
May I be assigned to this issue?

**Comment by jsvigneshkanna** [comment]
Hi @mpeiffer ,

Sure you can work on this, assigning you this issue

**Comment by biohazard2117** [comment]
I did the same type of job in previous issue. So I can do it lot faster , may I be assigned the issue ? @jsvigneshkanna

**Comment by jsvigneshkanna** [comment]
@biohazard2117 ,
Apologies! As mpeiffer as requested first

Anyways we will raise new feature/issue requests for the website and different tailwind components in some time

Follow this repo for faster updates

**Comment by mpeiffer** [comment]
@jsvigneshkanna I opened PR #31 for this issue.
