### ISSUE TITLE
Retain github and linkedin social icons in mobile 

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#179]
### Bug Title

Social icons in mobile view

### Description of BUG

We need to have only GitHub and LinkedIn social media icons on all pages, as it doesnt look nice to have 6 icons for mobile view

This is only gor mobile view and the styling changes should be made in socialButton component tailwindCSS 

### Reporduction URL of bug

Nill

### Bug Issue Type

Frontend

### Screenshot of the issue if in UI/ Document

![image](https://user-images.githubusercontent.com/42484705/197316927-1c290af3-0b59-47c7-a9b9-88079a9da1f9.png)

### Are you taking this issue fix

Nill

**Comment by eddybruv** [comment]
Hello @jsvigneshkanna, I'm new here
can I work on this task while I try to familiarise myself with the code base?

**Comment by jsvigneshkanna** [comment]
Welcome @eddybruv 
Go through the codebase and play around it, check how tailwind components are showcased

Let me know in any issues if you can take those too

**Comment by jsvigneshkanna** [comment]
@eddybruv 

Please let me know if any help needed, this issue needs to fixed with priority as this reduces the UX of product

**Comment by eddybruv** [comment]
Just facing some power issues, should be resolved before evening, sorry 😅

**Comment by jsvigneshkanna** [comment]
No worries!
