### ISSUE TITLE
span text overflow in small screen

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#188]
### Bug Title

span text overflow

### Description of BUG

In homepage banner we have a link `learn more ->` which is span element
This looks perfect in big screens, but the text is not looking as expected in mobile view port (width <380px).

Expected:
- We need the link text as a whole , and needs to in next line

### Bug Issue Type

Frontend

### Screenshot of the issue if in UI/ Document

![image](https://user-images.githubusercontent.com/42484705/197352313-77eca56f-eb72-4775-bbe3-2ac1f70bd797.png)

### Are you taking this issue fix

No

**Comment by nitoC** [comment]
can you assign this to me?

**Comment by jsvigneshkanna** [comment]
Yes sure @nitoC , please go ahead

**Comment by jsvigneshkanna** [comment]
Closeing as completed
