### ISSUE TITLE
Add github forks/ stars widget in website homepage

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#189]
### Feature Title

Add github forks/ stars widget

### Description

- We need to GitHub stars/ forks widget in homepage inside homebanner.js component
- It needs to position as displayed in below screenshot

### Motivation

Displaying Github forks/ stars in webpage would bring more audiences

### Issue Type

Backend

### Screenshot of the feature if done ?

![image](https://user-images.githubusercontent.com/42484705/197352646-b47c9d17-eede-47c2-b230-10b27f958a60.png)

### Are you taking this fetaure implementaion

Up for grabs

**Comment by harsh0620** [comment]
hi @jsvigneshkanna , Please assign me this task.

**Comment by jsvigneshkanna** [comment]
Hi @harsh0620 
Thank you for checking this repo, please make sure not to display widget in mobile and style in tailwindcss (hope it don't have many stylings)

**Comment by Ishikasaraf20** [comment]
hey @jsvigneshkanna can you assign this issue to me i can work on it

**Comment by jsvigneshkanna** [comment]
@Ishikasaraf20 , can you please check other open issues
This issue is solved
