### ISSUE TITLE
New license page should be added

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#190]
### Feature Title

New license page

### Description

- We need to add new page which reads the **_MIT LICENSE_** which we are using in this repo
- The page should be under new legal folder (NEXTJS routing)
- The new page URL should be /legal/license

1. The background color should be of component page (https://tailwindcsscomponents.vercel.app/components) and white text color with horizontal padding same as navbar
2. The page should be styled in tailwindCSS and needs to mobile responsive

For license content, refer https://github.com/jsvigneshkanna/tailwind_ui_components/blob/master/LICENSE

### Motivation

license page is must when we open this website to wide audience 

### Issue Type

Frontend

### Screenshot of the feature if done ?

nill

### Are you taking this fetaure implementaion

Up for grabs

**Comment by mnosov622** [comment]
Hi @jsvigneshkanna !

I would love to work on this issue.

Could you assign it to me, please?

**Comment by jsvigneshkanna** [comment]
Hi @mnosov622 ,
Sure, please go ahead!

**Comment by mnosov622** [comment]
Thank you !

What image can I add to license page?

**Comment by jsvigneshkanna** [comment]
@mnosov622 , for now we can use below image
![image](https://user-images.githubusercontent.com/42484705/197355585-fae41acb-a558-42a6-9b87-191c3f26c3cd.png)

And the license page will be linked to footer license link

NOTE: please make sure the page/ component(as per correct term) should be styled in tailwindCSS as the website itself is for tailwindCSS components

**Comment by mnosov622** [comment]
Yes, got it!

Basically, I need to make page similar to documentation page: text on the left and image(that you provided) on the right?
![image](https://user-images.githubusercontent.com/73063742/197355881-05c66a97-d02c-4bb9-836d-3b7414466a3e.png)

**Comment by jsvigneshkanna** [comment]
Yes flex-row in desktop and flex-column in mobile

**Comment by mnosov622** [comment]
Sure ! Got it.

One more question, please.

So the link to license should be only in the footer ?

**Comment by jsvigneshkanna** [comment]
Yes, for now we only redirection from footer 

This would be enhanced later with more pages coming

**Comment by mnosov622** [comment]
Sure, got it !

**Comment by mnosov622** [comment]
Hi @jsvigneshkanna !

Kindly review my PR, please and let me know :)
