### ISSUE TITLE
New about-us page to be created

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#191]
### Feature Title

New about-us page

### Description

We need to add new `about us` page inside nextjs page folder with below content

1. Our website motivation - refer: https://github.com/jsvigneshkanna/tailwind_ui_components#motivation
2. Solution we are providing - refer: https://github.com/jsvigneshkanna/tailwind_ui_components#solution
3. Build by contributors for contributors
4. Contributors image - refer: https://github.com/jsvigneshkanna/tailwind_ui_components#contributors-

### Design
1. follow https://tailwindcsscomponents.vercel.app/components page background gradient
2. text color should be white
3. horizontal padding should be same as navbar
4. mobile friendly
5. Exclusively styled with tailwindCSS

The new page should have navbar and footer component

### Motivation

About us page makes the project cooler 😎

### Issue Type

Frontend

### Screenshot of the feature if done ?

nill

### Are you taking this fetaure implementaion

Up for grabs

**Comment by deepaksuthar40128** [comment]
can you assign it to me?

**Comment by jsvigneshkanna** [comment]
Welcome back @deepaksuthar40128 , please go ahead

Add your own creativity on this page additional to mentioned stylings (need to be in tailwindCSS as the website itself for tailwindCSS components 🤪)

**Comment by deepaksuthar40128** [comment]
can i update the existing about us page and add above features?

**Comment by jsvigneshkanna** [comment]
Yes @deepaksuthar40128 that would work

**Comment by jsvigneshkanna** [comment]
@deepaksuthar40128 , we dont have existing aboutus page. We need to create new one
