### ISSUE TITLE
[FEATURE]: New Feature Card component

### ISSUE THREAD

**Issue by richardnikolas** [jsvigneshkanna/tailwind_ui_components#203]
### Description

Creating a new Feature Card component using Tailwind! 

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/20261986/197395987-ace5a6b6-af03-4898-a490-9748241aa83a.png)

### Are you taking this fetaure implementaion

Yes

**Comment by richardnikolas** [comment]
@jsvigneshkanna could you add the tags for Hacktoberfest, please?

**Comment by jsvigneshkanna** [comment]
Great @richardnikolas ,
BTW welcome to our cooleer Project 🥂
