### ISSUE TITLE
[FEATURE]: Stepper Component

### ISSUE THREAD

**Issue by RakshaPawar108** [jsvigneshkanna/tailwind_ui_components#207]
### Description

Horizontal Stepper Component for Multi-Step FormsHorizontal

### Screenshot of the tailwind component

![Screenshot (149)](https://user-images.githubusercontent.com/30971358/197401335-d4d19c10-66b9-4dce-9a8b-cd8ab5e4f0a7.png)

### Are you taking this fetaure implementaion

Yes

**Comment by RakshaPawar108** [comment]
Please assign this issue to me

**Comment by jsvigneshkanna** [comment]
Hi @RakshaPawar108 ,

Great you took new component. Please follow below instruction for folder structure.

- The final code should be placed under path tailwind_components/forms with file name as multi_form_horizontal_progress.jsx
- The file as to be imported to tailwind_components/forms /collection.js file as per example and added to the formCollections list
- Post these process, go to components tab (components/forms) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/
