### ISSUE TITLE
[Feature]: Alert Box

### ISSUE THREAD

**Issue by Krishnansh5** [jsvigneshkanna/tailwind_ui_components#209]
### Feature Title

Error/Warning Alert

### Description

A different looking alert box

### Motivation

Adding variety to alert boxes.

### Issue Type

Frontend

### Screenshot of the feature if done ?

![Screenshot from 2022-10-23 21-45-59](https://user-images.githubusercontent.com/97296908/197403394-346d24a0-9623-4eaf-983d-93e166c29c31.png)

### Are you taking this fetaure implementaion

Yes

**Comment by jsvigneshkanna** [comment]
Hi @Krishnansh5 , go ahead

- The final code should be placed under path tailwind_components/alerts with file name as sample_alert.jsx
- The file as to be imported to tailwind_components/alerts/collection.js file as per example and added to the alertCollections list
- The alert should close on clicking cross icon
- Post these process, go to components tab (components/alert) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

**Comment by Krishnansh5** [comment]
I have opened a PR for this issue
