### ISSUE TITLE
Need to check grammar and clean the text in document

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#211]
### Bug Title

Grammar check

### Description of BUG

We have added new documentation page, where we need to do grammar check and add/ remove words to make users understand the document with ease

### Reporduction URL of bug

https://tailwindcsscomponents.vercel.app/documentation

### Bug Issue Type

Documentation

### Screenshot of the issue if in UI/ Document

nill

### Are you taking this issue fix

No

**Comment by aiden5221** [comment]
can you please assign this issue to me

**Comment by jsvigneshkanna** [comment]
Please go ahead @aiden5221

**Comment by aiden5221** [comment]
PR created.
