### ISSUE TITLE
Correct the display of text in footer

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#213]
### Bug Title

Display issue in footer

### Description of BUG

The footer's `follow us` text is wrapped to 2 lines only in codepen page. We need to check why the issue is happening in codepen page and rectify that to display that as other pages

NOTE: THIS ISSUE IS HAPPENING ONLY FOR MOBILE VIEW PORT - width < 420px

### Reporduction URL of bug

/component/buttons

### Bug Issue Type

Frontend

### Screenshot of the issue if in UI/ Document

![image](https://user-images.githubusercontent.com/42484705/197409180-af31d201-1126-4b11-95ab-194de47c25b6.png)

### Are you taking this issue fix

No

**Comment by GAURCODER** [comment]
@jsvigneshkanna can you assign this issue to me

**Comment by jsvigneshkanna** [comment]
Sure @GAURCODER 

BTW, halpy diwali

**Comment by GAURCODER** [comment]
@jsvigneshkanna Happy Diwali
