### ISSUE TITLE
[Feature]: Add automatic releases

### ISSUE THREAD

**Issue by Dun-sin** [jsvigneshkanna/tailwind_ui_components#215]
### Feature Title

Add automatic releases

### Description

I noticed that the releases are done manually
How about create an automatic release, that happens whenever some contributes to this project, it will use the conventional commit. I see you already use conventional commits anyway.

Here's a link for reference: 
[Set Automatic Release (Skip Commitizen)](https://youtu.be/QZdY4XYbqLI)

> Note: Can only be done by repo owner

### Motivation

Helps with not manually updating releases

### Issue Type

Documentation

### Are you taking this fetaure implementaion

No

**Comment by jsvigneshkanna** [comment]
Hi @Dun-sin 
Looks good idea, it would rather reduce my relase headache 🤣

Can you please take this issue

**Comment by Dun-sin** [comment]
> Hi @Dun-sin Looks good idea, it would rather reduce my relase headache 🤣
> 
> Can you please take this issue

Can only be done by you, only you have the rights to do it
