### ISSUE TITLE
Fix grammar in readme file

### ISSUE THREAD

**Issue by akshayrs3** [jsvigneshkanna/tailwind_ui_components#23]
Observed a few issues with the grammar in the readme. Some articles are missing and sentences would be cleaner and read better with their presence.

**Comment by jsvigneshkanna** [comment]
Thanks @akshayrs3  for bringing this issue, can you please pull latest readme changes and run one final grammar check

**Comment by jsvigneshkanna** [comment]
Thank you @akshayrs3

**Comment by akshayrs3** [comment]
@jsvigneshkanna no worries! Thank you :)
