### ISSUE TITLE
[Bug]: Logo text is dark and not very visible

### ISSUE THREAD

**Issue by eddybruv** [jsvigneshkanna/tailwind_ui_components#235]
### Bug Title

[Bug]: Logo text is dark and not very visible

### Description of BUG

The logo text is not visible on its current background

### Bug Issue Type

Frontend

### Screenshot of the issue if in UI/ Document

![image](https://user-images.githubusercontent.com/80322163/197542367-93519a62-6e00-4f10-a778-63738cca7d45.png)

### Are you taking this issue fix

yes

**Comment by octosapien** [comment]
I would love to work on this .
Please assign me this issue .
