### ISSUE TITLE
[BUG]: Contributors list in readme not getting updated

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#24]
### Description

The contributors list in bottom of README file not getting updated dynamically when new contributors come. 

### Motivation

This should be fixed as contributors are sole backbone of this cool project

### Issue Type

Documentation

### Are you taking this fetaure implementaion

No, This is up for grabs

**Comment by jsvigneshkanna** [comment]
Original count of contributors:
![image](https://user-images.githubusercontent.com/42484705/196029589-5748a79c-fd49-497e-a2ed-03bcc8f6603e.png)

but in readme
![image](https://user-images.githubusercontent.com/42484705/196029598-d3823134-96b5-4635-ae25-103ecca0afdd.png)

**Comment by akshayrs3** [comment]
@jsvigneshkanna 
I believe the image pasted in the readme is a static image, which was generated one time. When it was generated, it had just 3 contributors, and then it was pasted. the static image does not update dynamically. 

It must have been created using this 
https://contrib.rocks/preview?repo=angular%2Fangular-ja

**Comment by jsvigneshkanna** [comment]
Good findings @akshayrs3 
If you can fix this, can i assign this issue under your name?

**Comment by akshayrs3** [comment]
@jsvigneshkanna I believe it should sync automatically. they must have built the app in that way. 
https://dev.to/lacolaco/introducing-contributors-img-keep-contributors-in-readme-md-gci

let's check tomorrow and see if it updates.

**Comment by jsvigneshkanna** [comment]
Sure @akshayrs3 ,

Will assign this issue to your name, please check tomorrow whether the list is getting updated tomorrow. If not please fix this
