### ISSUE TITLE
Typos in website! 

### ISSUE THREAD

**Issue by mcctrix** [jsvigneshkanna/tailwind_ui_components#244]
### Bug Title

typos in texts

### Description of BUG

I would like to fix some of the typos in the website as well as fixing some UI glitches on mobile side. such as options in navbar menu have too much margin or padding. there are some improvement can be made 

### Bug Issue Type

Frontend

### Are you taking this issue fix

Yes

**Comment by jsvigneshkanna** [comment]
Sure @mcctrix 
Please proofread the texts and regarding UI changes, don't make major changes . just include margin/padding alone

Please star this repo to make it cooler

**Comment by mcctrix** [comment]
![image](https://user-images.githubusercontent.com/42296139/197769500-fc001e1e-5efa-4264-834d-741feacf4fbc.png)
These margin/padding are looking a bit long.

**Comment by jsvigneshkanna** [comment]
Oh, then we can try reducing the padding and margins.
Please go ahead

**Comment by mcctrix** [comment]
![image](https://user-images.githubusercontent.com/42296139/197770013-cc9dffdd-0dc4-42d3-808c-6b087932166b.png)
Description: "There are lots of components such as Button, Form, Feature Card etc. which can save lot of time for a front end dev. you can access them from [Here](https://tailwindcsscomponents.vercel.app/components)"

**Comment by jsvigneshkanna** [comment]
@mcctrix , you can raise PR with the changes. I will check the changes done there.
