### ISSUE TITLE
[Bug]: Navbar Links are not clickable via their hover backgrounds

### ISSUE THREAD

**Issue by Athi223** [jsvigneshkanna/tailwind_ui_components#247]
### Bug Title

Navbar Links are not clickable via their hover backgrounds

### Description of BUG

The hoverable area around the links (colored purple when hovered) is not clickable to navigate to the link. However, it should also trigger the link click, as it is a hover effect and user should be able to click that too.

Note: I'd like to contribute to this, if you feel this needs to be fixed

### Reporduction URL of bug

https://tailwindcsscomponents.vercel.app/

### Bug Issue Type

Frontend

### Screenshot of the issue if in UI/ Document

Hover Background is not Clickable:
![image](https://user-images.githubusercontent.com/31766648/197789927-2afee0ed-853d-4381-81e1-adcefab4cc97.png)

Only Text is Clickable:
![image](https://user-images.githubusercontent.com/31766648/197790009-d7e38112-4c6f-45a6-baa8-abb3799cb71a.png)

### Are you taking this issue fix

Yes

**Comment by jsvigneshkanna** [comment]
Sure @Athi223 , please go ahead
