### ISSUE TITLE
[Bug]: when screen is less than 900px button contains git star and fork is not displayed

### ISSUE THREAD

**Issue by munyanezaarmel** [jsvigneshkanna/tailwind_ui_components#249]
### Bug Title

[Bug]: when screen is less than 900px button contains git star and fork is not displayed

### Description of BUG

for small devices tablets and smartphones button of git star and fork is displayed to none means are not showing up for small devices

### Reporduction URL of bug

https://tailwindcsscomponents.vercel.app/

### Bug Issue Type

Frontend

### Screenshot of the issue if in UI/ Document

![image](https://user-images.githubusercontent.com/73389979/197869406-25ef58ee-2e92-4928-acab-2ef0de53356a.png)

### Are you taking this issue fix

YES

**Comment by codeboyfriend** [comment]
Can I work on it?

**Comment by jsvigneshkanna** [comment]
Hi @munyanezaarmel , its made intentionally not to display gitstats in mobile devices
 You can try adding that stats in hamburger menu instead

**Comment by jsvigneshkanna** [comment]
For mobile devices alone

**Comment by codeboyfriend** [comment]
I'll make a PR soon

**Comment by munyanezaarmel** [comment]
@jsvigneshkanna am not getting well hamburger menu means it should be displayed under FAQS

**Comment by jsvigneshkanna** [comment]
@munyanezaarmel yeah that would be good idea or above contributors list in about us page centered

**Comment by jsvigneshkanna** [comment]
Any updates @munyanezaarmel/ @codeboyfriend  ?

**Comment by AmanJain18** [comment]
Assign it to me and let me know where i should include it in mobile view screen sizes ?

**Comment by jsvigneshkanna** [comment]
@AmanJain18 , display it below contributors text and above contributors images in about US page

This should be displayed for all screens.

![image](https://user-images.githubusercontent.com/42484705/198356517-24dd161e-4fb7-4555-a403-e9fd0467b115.png)

**Comment by AmanJain18** [comment]
Fixed issue merge PR ✌️🙂

**Comment by AmanJain18** [comment]
Check for All mobile and tab screen size, its working perfectly...
Kindly please add hacktoberfest-accepted label for my PR
Thank You...
