### ISSUE TITLE
[Bug]: Bootstrap misspelled incorrect

### ISSUE THREAD

**Issue by munyanezaarmel** [jsvigneshkanna/tailwind_ui_components#250]
### Bug Title

[Bug]: Bootstrap misspelled incorrect

### Description of BUG

 tailwind bootsrap instead of bootstrap in follow section us section

### Reporduction URL of bug

https://tailwindcsscomponents.vercel.app/

### Bug Issue Type

Frontend

### Screenshot of the issue if in UI/ Document

![image](https://user-images.githubusercontent.com/73389979/197936519-682a5b70-7bee-475a-bcb1-991e964832fc.png)

### Are you taking this issue fix

YES

**Comment by jsvigneshkanna** [comment]
@munyanezaarmel go ahead with fix

**Comment by munyanezaarmel** [comment]
@jsvigneshkanna done check it
