### ISSUE TITLE
Retain github and linkedin social icons in <900px view

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#255]
### Bug Title

Retain github and linkedin social icons

### Description of BUG

Retain github and linkedin social icons in <900px view

Hide other social icons which in less than 900 px view port

### Reporduction URL of bug

https://tailwindcsscomponents.vercel.app/

### Bug Issue Type

Frontend

### Screenshot of the issue if in UI/ Document

![image](https://user-images.githubusercontent.com/42484705/198036574-98558ed6-4ae6-47a1-8273-6b1d0f58f135.png)

### Are you taking this issue fix

No

**Comment by AmanJain18** [comment]
Can u assign it to me Please

**Comment by jsvigneshkanna** [comment]
@AmanJain18 sure, refer mobile view port design!
