### ISSUE TITLE
increase width for div for view 400 to 900px

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#256]
### Bug Title

increase width

### Description of BUG

increase width for div for view 400 to 900px

the horizontal margins should be same as navbars for viewport <900px

### Bug Issue Type

Frontend

### Screenshot of the issue if in UI/ Document

![image](https://user-images.githubusercontent.com/42484705/198036893-3534f10b-fbdc-4e12-bb1f-8c6a0d9b19d6.png)

### Are you taking this issue fix

No

**Comment by vanshikaa-agarwal** [comment]
i would like to work on this

**Comment by vanshikaa-agarwal** [comment]
please assign this issue to me

**Comment by jsvigneshkanna** [comment]
Sure @vanshikaa-agarwal , go ahead

take reference from mobile view port for design! let me know if any help needed 
BTW please star this repo (huge diff between forks and stars 😁)

**Comment by AmanJain18** [comment]
Hey, Could you tell more clearly what to be fixed...
and assign it to me.

**Comment by jsvigneshkanna** [comment]
Hi @AmanJain18 
In the ipad view port, the div which is shown in the screenshot is not having any harizontal adding 

This should like what is displayed in mobile screen

**Comment by jsvigneshkanna** [comment]
This div is in components page

**Comment by AmanJain18** [comment]
Okay will try to fix and implement that
And i had fixed issue #255, can u merge my PR...

**Comment by AmanJain18** [comment]
Issue Fixed, Please check and update me for any additional changes
