### ISSUE TITLE
[FEATURE]: Expandable input field

### ISSUE THREAD

**Issue by Znoy108x** [jsvigneshkanna/tailwind_ui_components#263]
### Description

I  can create expandable input field . 
On hovering it all the input fields will be shown

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/75539409/198333603-9a166726-83c2-4401-bb72-3152056fc987.png)
![image](https://user-images.githubusercontent.com/75539409/198333626-025f1815-f70a-4682-be4b-381d391c2987.png)

### Are you taking this fetaure implementaion

Yes

**Comment by jsvigneshkanna** [comment]
Hi @Znoy108x ,
Please make sure it's not copied and pasted from somewhere. we follow `strict guideline for plagiarism`. 
Add this under forms components folder

**Comment by Znoy108x** [comment]
@jsvigneshkanna don't worry i have made it by  myself using tailwind

**Comment by Znoy108x** [comment]
@jsvigneshkanna  There are some errors while installing ( npm i )  the project ??

**Comment by jsvigneshkanna** [comment]
share the screenshot

**Comment by jsvigneshkanna** [comment]
I dont have any errors @Znoy108x

**Comment by Znoy108x** [comment]
![image](https://user-images.githubusercontent.com/75539409/198571883-ccc89b43-f27b-4490-9260-54b630921323.png)

**Comment by maemreyo** [comment]
> @jsvigneshkanna ![image](https://user-images.githubusercontent.com/75539409/198571883-ccc89b43-f27b-4490-9260-54b630921323.png)

DId you try to remove `node_modules` first, then `npm i`.

**Comment by Znoy108x** [comment]
no ! but i solved that issue by running "yarn install"
