### ISSUE TITLE
[Bug]: Responsiveness 

### ISSUE THREAD

**Issue by RoshaanAli** [jsvigneshkanna/tailwind_ui_components#267]
### Bug Title

Responsiveness Issue

### Description of BUG

Social icons are hiding in responsiveness.

Kindly assign me this issue.

### Bug Issue Type

Frontend

### Screenshot of the issue if in UI/ Document

![image](https://user-images.githubusercontent.com/25253872/198596457-589f354c-fd3a-4aa5-8f3c-8885a2bf2fb8.png)

### Are you taking this issue fix

yes

**Comment by jsvigneshkanna** [comment]
Sure @RoshaanAli , please go agead, and also star the repo to make it cooler

**Comment by AmanJain18** [comment]
@RoshaanAli  Check bug issue #255 , it is made just like that to hide in mobile and tab screen sizes...

**Comment by AmanJain18** [comment]
@jsvigneshkanna If social icon is to be shown at <900px view port than assign it to me, as i know where to make changes and fixed issue... has work on it Bug #255

**Comment by AmanJain18** [comment]
Issue Fixed....

**Comment by jsvigneshkanna** [comment]
@AmanJain18 , here the github and linkedin icons should only be visible in view port < 900px and have some horizontal padding between 2 icons

**Comment by AmanJain18** [comment]
> @AmanJain18 , here the github and linkedin icons should only be visible in view port < 900px and have some horizontal padding between 2 icons

When the screen size is less the <900px only github and linkedin icon should be visible and rest icon should be hidden right ?
