### ISSUE TITLE
Improving Social media section

### ISSUE THREAD

**Issue by Mahich123** [jsvigneshkanna/tailwind_ui_components#269]
I would like to improve the social media section this one : 
![image](https://user-images.githubusercontent.com/69717681/198712720-8b1130b8-7f79-4546-9af0-4a426a6eb04d.png)
can you assign me ?

**Comment by jsvigneshkanna** [comment]
@Mahich123 , please go ahead.
Don't make big changes to not lose the main essence
You can change the padding, margins, borders

Also star the rep

**Comment by Mahich123** [comment]
@jsvigneshkanna  Made pr can you check the changes ....
