### ISSUE TITLE
Use JS to keep year updated

### ISSUE THREAD

**Issue by developer-diganta** [jsvigneshkanna/tailwind_ui_components#277]
![image](https://user-images.githubusercontent.com/65999534/198955225-1ecee1b4-7a14-480f-9aed-d809c923710b.png)
The year can be kept updated using JS instead of hardcoding. If this issue is relevant, can I work on it?

**Comment by jsvigneshkanna** [comment]
@developer-diganta , great check please go ahead. Give a star to repo!
