### ISSUE TITLE
[Feature]: Improve FAQ section

### ISSUE THREAD

**Issue by mnosov622** [jsvigneshkanna/tailwind_ui_components#280]
### Feature Title

Improve UX when exploring FAQ section

### I have 3 things, that I would love to add:

1) Add transition, so that description will appear smoothly. Now it's appearing the same moment you click on arrow icon.

2) When 1 item is selected, close others. This will allow user to focus only on one item at a time.

For now, we can open all tabs, which is a bit messy, no offense, please :) 

![image](https://user-images.githubusercontent.com/73063742/199129940-c9593f67-3e44-4597-a9e1-2693657277f0.png)

3) Add cursor - pointer when user hovers on item. It will be easier for user, when he can open item description by clicking anywhere on the item (not only on arrow icon).

I would be happy to improve UX for your graceful website, that I've been following up for the last 2 weeks :)

### Motivation

Make website look prettier :)

### Issue Type

Frontend

### Are you taking this fetaure implementaion

Yes

**Comment by mnosov622** [comment]
Kindly, assign this issue to me :)

**Comment by jsvigneshkanna** [comment]
@mnosov622 , great check
Please go ahead! Will love to see the end result.
If you want, you can break these 3 points to smaller parts and raise PRs for them.

**Comment by mnosov622** [comment]
Thank you !

Yes. Can I make one PR but add new commit with each step implemented ?

**Comment by jsvigneshkanna** [comment]
Am daying, creating 3 PRs for each point you have mentioned

**Comment by mnosov622** [comment]
Uh, it's just that I  need one PR for college course. Is it okay, please?

**Comment by jsvigneshkanna** [comment]
Yeah sure please go aheah @mnosov622

**Comment by mnosov622** [comment]
Thank you !

Appreciate it :)

**Comment by mnosov622** [comment]
Hi @jsvigneshkanna !

For some reason description is not opening locally, do you know what might be an issue here?

https://user-images.githubusercontent.com/73063742/199382829-ebbc87f8-2270-4197-903e-0a7b18048952.mp4

Thank you!

**Comment by jsvigneshkanna** [comment]
It happens in local, need to find the issue. But works in production

**Comment by mnosov622** [comment]
Oh, but how do I test it then ?(

**Comment by AmanJain18** [comment]
Implemented feature and fix other different known issue.. ☺️

**Comment by mnosov622** [comment]
@AmanJain18 sorry, but this issue was assigned to me, why would you do it ? :)

**Comment by AmanJain18** [comment]
Issue ic completed... Set it to closed
