### ISSUE TITLE
[Feature]:  new CODE OF CONDUCT file

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#29]
#  Feature Title

add code_of_conduct file

# Description

Add new file CODE_OF_CONDUCT.md under root directory which has standard rules to be followed in open source

Please add `vkrishitaran@gmail.com` email ID wherever required in contact details in above file

# Motivation

This file will help to bring standard behavior among the contributors

# Issue Type

Documentation

# Screenshot of the feature if done ?

_No response_

# Are you taking this fetaure implementaion

No, this is up for grabs

# PR Requirement:

- Please check the above requirements are met
- Always create new branch on forked repo from master to avoid and error while merging the fix
- Please Star this repo while forking as that would increase this repo's visibility

Cheers 🎉

**Comment by ferrorenan** [comment]
@jsvigneshkanna 
Hey friend, I created a PR to solve this issue. Could you take a look please!?
The PR link: https://github.com/jsvigneshkanna/tailwind_ui_components/pull/30

**Comment by jsvigneshkanna** [comment]
Closing this issue as completed
