### ISSUE TITLE
[Bug]: Unresponsive navbar

### ISSUE THREAD

**Issue by chibuike-19** [jsvigneshkanna/tailwind_ui_components#33]
### Bug Title

Unresponsive navbar

### Description of BUG

Navbar is unresponsive on mobile devices.

### Bug Issue Type

Frontend

### Screenshot of the issue if in UI/ Document

![tailwind-comp](https://user-images.githubusercontent.com/94564639/196228564-d56d34af-9c77-4c7d-9ddf-57ccfa8d0d3c.png)

### Are you taking this issue fix

Yes

**Comment by rohitsinghind** [comment]
hey, can u assign this to me

**Comment by chibuike-19** [comment]
I'm not a maintainer, I'm also asking to be assigned to this issue

**Comment by jsvigneshkanna** [comment]
@chibuike-19 , am assigning this issue for navbar
Please fix navbar responsiveness

**Comment by jsvigneshkanna** [comment]
@rohitsinghind ,
Can you please check the homepage banner responsive issue and fix that

Appreciate you for checking this

**Comment by chibuike-19** [comment]
> @chibuike-19 , am assigning this issue for navbar Please fix navbar responsiveness

Ok @jsvigneshkanna I'm working on it now

**Comment by jsvigneshkanna** [comment]
@chibuike-19 ,
let me know if you need help

**Comment by jsvigneshkanna** [comment]
Hi @saroshfarhan ,

Nothing is Mundane in open source 😜

Development steps:

1. fork the repo and checkout your forked repo branch in local (git checkout ``)
2. cd tailwind_ui_components
**3. npm install (this will install all the dependencies)
4. npm run dev (this will start the local server)**
5. make changes and play around with the code
6. once changes are tested please commit those 
7. and raise a pull request to my repo

**Comment by jsvigneshkanna** [comment]
@chibuike-19 ,

Any update? let me know if any problem facing

**Comment by saroshfarhan** [comment]
> Hi @saroshfarhan ,
> 
> Nothing is Mundane in open source 😜
> 
> Development steps:
> 
>     1. fork the repo and checkout your forked repo branch in local (git checkout ``)
> 
>     2. cd tailwind_ui_components
> 
>     3. **npm install (this will install all the dependencies)**
> 
>     4. **npm run dev (this will start the local server)**
> 
>     5. make changes and play around with the code
> 
>     6. once changes are tested please commit those
> 
>     7. and raise a pull request to my repo
> 
> 
> check for issue or features and start contributing to our cool project and become a cooler contributor 😎

@jsvigneshkanna thank you so much for this step-by-step guide, really appreciated 🚀

**Comment by jsvigneshkanna** [comment]
@saroshfarhan ,
Check for easy issues in issue page
