### ISSUE TITLE
[Bug]: make homepage banner responsive to mobile screens 

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#34]
### Bug Title

Unresponsive homepage banner

### Description of BUG

- Unresponsive homepage banner 
- The responsiveness should for viewport 768px and 460pm
- Fix the stylings in respective css file using media query

### Reporduction URL of bug

https://tailwindcsscomponents.vercel.app/

### Bug Issue Type

Frontend

### Screenshot of the issue if in UI/ Document

Nill

### Are you taking this issue fix

No

**Comment by FilipePfluck** [comment]
I can do this. Assign me please.

**Comment by FilipePfluck** [comment]
https://github.com/jsvigneshkanna/tailwind_ui_components/pull/37

**Comment by jsvigneshkanna** [comment]
Thank you @FilipePfluck

**Comment by jsvigneshkanna** [comment]
@FilipePfluck ,
Check for other issue and dont forget to star this repo and keep this in watchlist to get new issues notified quicker
