### ISSUE TITLE
[Feature]: Style the component page

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#38]
### Feature Title

Component page styling

### Description

We have added new component page where we embed codepen and this page needs styling as there would be multiple codepens in single page

URL - https://tailwindcsscomponents.vercel.app/components

### Motivation

As component page is sole for our website, this requires proper styling

### Issue Type

Frontend

### Screenshot of the feature if done ?

Nill

### Are you taking this fetaure implementaion

No

**Comment by sanket-16** [comment]
Hey , I would love to work on the issue!  
Also instead of codepen would you be interested in tailwind docs type of display for components or i can just work with codepen?

**Comment by jsvigneshkanna** [comment]
Hi @sanket-16 ,

I would like to see the tailwind docs type display too

Assigning you this issue, please share me the screenshot of final design with tailwind docs type display

**Comment by jsvigneshkanna** [comment]
Hi @sanket-16 , any updates

Let me know is help needed

**Comment by sanket-16** [comment]
Do check out https://tailwindui.com/components

I'm in the middle of implementing this layout. Lemme know your thoughts.

**Comment by jsvigneshkanna** [comment]
Looks good @sanket-16 ,
Do check the existing components card page by recreating this layout and make sure existing dark mode color palete used

Aprreciate that !

**Comment by sanket-16** [comment]
Hey @jsvigneshkanna ,
Here's something I whipped up.. Lemme know your thoughts! Added bonus it's responsive and already written in tailwind!

![gif](https://media1.giphy.com/media/9h96q9hWvbdvH84HsZ/giphy.gif?cid=790b7611a83c99270066845a5238ef40144aa329c5509b75&rid=giphy.gif&ct=g)

**Comment by jsvigneshkanna** [comment]
@sanket-16 
I would prefer to have the components in new pages rather than in homepage itself

Can you check live website now

**Comment by jsvigneshkanna** [comment]
The objective of this issue is to only make styling to `component_page` where it shows type of component/ image/ brief of that

**Comment by jsvigneshkanna** [comment]
@sanket-16 , something like that

![image](https://user-images.githubusercontent.com/42484705/197324059-ae2ca8b1-8d3b-479b-9ba3-77bd8fa175ff.png)

**Comment by sanket-16** [comment]
@jsvigneshkanna so is the design fine I'll just use the same card for displaying component types?

**Comment by jsvigneshkanna** [comment]
Yes

**Comment by sanket-16** [comment]
This good enough?
![image](https://user-images.githubusercontent.com/64531568/197328150-eafefe81-c286-4e3b-be87-b49747f0e88d.png)

**Comment by jsvigneshkanna** [comment]
@sanket-16 , what about having exisiting bg-color for cards but creating some text above and search buttons like that

**Comment by jsvigneshkanna** [comment]
@sanket-16 , this is because - I somehow like the existing minimalistic design but want some searching functions in component page like other website. Can you create that ?

![image](https://user-images.githubusercontent.com/42484705/197329341-6e12775f-a0c7-473c-9bd5-1adf11f50bc3.png)
