### ISSUE TITLE
[Bug]: Codepen prefill embed not working

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#39]
### Bug Title

Codepen prefill embed not working

### Description of BUG

Codepen prefill embed not loading after page refresh

### Reporduction URL of bug

https://tailwindcsscomponents.vercel.app/components

### Bug Issue Type

Frontend

### Screenshot of the issue if in UI/ Document

![image](https://user-images.githubusercontent.com/42484705/196340579-2eece7a3-ca6c-42e6-81a4-f802999d9335.png)

### Are you taking this issue fix

No

**Comment by GeorgeET15** [comment]
For me its working fine after reloading.

**Comment by jsvigneshkanna** [comment]
Hi @GeorgeET15 ,

bug reproduction step,

1. npm run dev (start the webpage fresh)
2. click `components` link in navbar and move to that page (you can see codepen loaded properly)
3. now come back to homepage
4. again follow step 2 where you will see page as shown in screenshot above

**Comment by GeorgeET15** [comment]
I would like to work on this issue can you assign this to me. Thank you

**Comment by jsvigneshkanna** [comment]
Yeah sure @GeorgeET15 ,

Do you know the issue/ fix to this?

We can have a conversation in discord (vigneshkanna#4052)

**Comment by GeorgeET15** [comment]
> Yeah sure @GeorgeET15 ,
> 
> Do you know the issue/ fix to this?
> 
> We can have a conversation in discord (vigneshkanna#4052)

Yes I found the issue.

**Comment by jsvigneshkanna** [comment]
@GeorgeET15 , let me know if help needed

**Comment by jsvigneshkanna** [comment]
@GeorgeET15 ,
Any update?

**Comment by GeorgeET15** [comment]
> @GeorgeET15 , let me know if help needed

Yeah sure. Thank you

**Comment by jsvigneshkanna** [comment]
Hi @GeorgeET15 , any updates?

**Comment by jsvigneshkanna** [comment]
@GeorgeET15 , closing this issue as it was in inactive state for 4 days
