### ISSUE TITLE
[Feature]: design about us page

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#40]
### Feature Title

Design about us page

### Description

The new page should be under nextjs standard of pages
The color schema can be taken from navbar and homepage banner

This page should have below points considered

1. What is tailwind bootstrap
2. Where you find us
3. Why we doing this project

### Motivation

About us page will give bigger picture of the project

### Issue Type

Frontend

### Are you taking this fetaure implementaion

No

**Comment by shrutilenka** [comment]
Hey @jsvigneshkanna , I am interested to work on this issue. I have prior experience with tailwind CSS. So could you pls assign this to me?

**Comment by jsvigneshkanna** [comment]
Hi @shrutilenka ,

Assing this issue to you name, please go through the website and repo docs to know more about this project

Also check other tailwind components issues

**Comment by shrutilenka** [comment]
thanks @jsvigneshkanna

**Comment by jsvigneshkanna** [comment]
Hi @shrutilenka 
Any updates, please let me know if any help needed

**Comment by shrutilenka** [comment]
> Hi @shrutilenka Any updates, please let me know if any help needed

Sorry sir due to some personal problems i am unable to contribute to this issue anymore.
