### ISSUE TITLE
single text tailwind button design

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#41]
### Feature Title

single text tailwind button design

### Description

Need to create code for single text button as per below image.

1. The final code should be placed under path `tailwind_components/buttons` with file name as `single_button.jsx`
2. The file as to be imported to `tailwind_components/buttons/collection.js` file as per example and added to the `buttonCollections` list
3. Post these process, go to components tab in website and check whether the codepen is updated

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196469066-adf2923e-eb8c-4b12-a568-78ec4d72e6db.png)

### Are you taking this fetaure implementaion

No

**Comment by PranshuNayak** [comment]
I want to work on this issue please assign

**Comment by jsvigneshkanna** [comment]
hi @PranshuNayak 
Please go aheah, also look for other issues and features too
