### ISSUE TITLE
Delete button tailwind design

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#42]
### Feature Title

Delete button tailwind design

### Description

Need to create code for delete text+icon button as per below image.

The final code should be placed under path tailwind_components/buttons with file name as delete_button.jsx
The file as to be imported to tailwind_components/buttons/collection.js file as per example and added to the buttonCollections list
Post these process, go to components tab in website and check whether the codepen is updated

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196469335-e695c5e0-9802-4a70-acb6-4fb7dd272aa1.png)

### Are you taking this fetaure implementaion

No

**Comment by zainbinfurqan** [comment]
@jsvigneshkanna  Can i work on this?

**Comment by jsvigneshkanna** [comment]
Sure @zainbinfurqan , please follow the instructions and the folder structure as it determines the code to be displayed in website's codepen

Let me know if you need any help. Also check for other issues to
