### ISSUE TITLE
[FEATURE]: Tailwind download button

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#43]
### Description

Need to create code for download now text+icon button as per below image.

The final code should be placed under path tailwind_components/buttons with file name as download_now1.jsx
The file as to be imported to tailwind_components/buttons/collection.js file as per example and added to the buttonCollections list
Post these process, go to components tab in website and check whether the codepen is updated

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196475181-cecc8db0-f0d2-4388-b779-be0ceff1720a.png)

### Are you taking this fetaure implementaion

No

**Comment by iamkennis** [comment]
I will work on this too

**Comment by jsvigneshkanna** [comment]
Thanks @iamkennis 
Follow the folder and file structure of sample given

**Comment by iamkennis** [comment]
okay
