### ISSUE TITLE
[FEATURE]: see-more tailwind button 

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#44]
### Description

Need to create code for `see more` button as per below image.

The final code should be placed under path tailwind_components/buttons with file name as see_more1.jsx
The file as to be imported to tailwind_components/buttons/collection.js file as per example and added to the buttonCollections list
Post these process, go to components tab in website and check whether the codepen is updated

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196475752-197cf012-12f7-45d7-b956-7aba6f6dfb54.png)

### Are you taking this fetaure implementaion

No

**Comment by iamkennis** [comment]
I want to work on this button

**Comment by iamkennis** [comment]
okay

**Comment by jsvigneshkanna** [comment]
@iamkennis check for other issues

**Comment by iamkennis** [comment]
okay
