### ISSUE TITLE
[FEATURE]: rectangle dropdown button in tailwindcss

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#45]
### Description

Need to create code for rectangle dropdown button button as per below image.

The final code should be placed under path tailwind_components/buttons with file name as rectangle_dropdown_button.jsx
The file as to be imported to tailwind_components/buttons/collection.js file as per example and added to the buttonCollections list
Post these process, go to components tab in website and check whether the codepen is updated

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196479749-d519c291-dead-4b66-8cd7-79e06baec59a.png)

### Are you taking this fetaure implementaion

No

**Comment by itsmenikhill** [comment]
I'd like to work on this

**Comment by jsvigneshkanna** [comment]
Hi @itsmenikhill ,
Am assigning to your name, please follow the folder structure instructions

Also look for others issues to solve

**Comment by jsvigneshkanna** [comment]
@itsmenikhill ,
For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

**Comment by itsmenikhill** [comment]
Hi @jsvigneshkanna do you want the button to display any options or just the button?

**Comment by jsvigneshkanna** [comment]
@itsmenikhill , yeah good thought

Its will be more good to show 1/2 options when clicked like dropdown menu

**Comment by jsvigneshkanna** [comment]
Perfect @itsmenikhill 

Does option open upon clicking button, if so you van go ahed with PR

Also check out this figma and raise issues for which you can build components with screenshot

https://www.figma.com/file/0eqV7t3UKKM14UeqCSfOZb/Essential-UI---Figma-Ui-Kit-(Community)?node-id=688%3A1988

**Comment by itsmenikhill** [comment]
Alright!
