### ISSUE TITLE
[FEATURE]: Setting button tailwind

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#46]
### Description

Need to create code for **SETTING** button as per below image.

The final code should be placed under path tailwind_components/buttons with file name as rectangle_setting.jsx
The file as to be imported to tailwind_components/buttons/collection.js file as per example and added to the buttonCollections list
Post these process, go to components tab in website and check whether the codepen is updated

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196483481-d9c2a9e9-9810-42fe-82b4-a7a3499e5836.png)

### Are you taking this fetaure implementaion

no

**Comment by zainbinfurqan** [comment]
@jsvigneshkanna  Can i work on this?

**Comment by jsvigneshkanna** [comment]
Hi @zainbinfurqan ,

Sure, please follow the instructions and the folder structure as it determines the code to be displayed in website's codepen 

Let me know if you need any help. Also check for other issues to

**Comment by jsvigneshkanna** [comment]
@zainbinfurqan ,

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons
