### ISSUE TITLE
[FEATURE]: Play button in tailwind

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#47]
### Description

Need to create code for play buttons with different size and shape as per below image.

The final code should be placed under path tailwind_components/buttons with file name as paly_buttons.jsx
The file as to be imported to tailwind_components/buttons/collection.js file as per example and added to the buttonCollections list
Post these process, go to components tab in website and check whether the codepen is updated

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196486885-35684464-e901-4461-bc0f-0bdcd76c4c6b.png)

### Are you taking this fetaure implementaion

No

**Comment by Anuran12** [comment]
@jsvigneshkanna i would like to work on this

**Comment by jsvigneshkanna** [comment]
@Anuran12 ,

Assigning your name
