### ISSUE TITLE
[FEATURE]: Arrow buttons in tailwind

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#48]
### Description

Need to create code for ARROW button as per below image.

The final code should be placed under path tailwind_components/buttons with file name as solid_arrow_buttons.jsx
The file as to be imported to tailwind_components/buttons/collection.js file as per example and added to the buttonCollections list
Post these process, go to components tab in website and check whether the codepen is updated

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196489082-7eb0a7ba-cdb3-452c-bcd0-f3a6f8155482.png)

### Are you taking this fetaure implementaion

No

**Comment by jsvigneshkanna** [comment]
@Kabiirk ,

You need to build this in html (play with - https://play.tailwindcss.com/)

The code has to be created as per below sample folder structure:

https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

**Comment by Kabiirk** [comment]
Thanks ! Per my understanding, I would need to copy the result HTML(from play.tailwind.com) and make a normal PR right ?

**Comment by jsvigneshkanna** [comment]
Yes @Kabiirk 
Please refer this PR https://github.com/jsvigneshkanna/tailwind_ui_components/pull/58/files

This will give picture on where you need to create file and modify

**Comment by jsvigneshkanna** [comment]
@Kabiirk ,
any updates, let me know if any help needed

**Comment by Kabiirk** [comment]
@jsvigneshkanna 
Sure, I'll let you know if i need any help. I'm employed full time so I usually start working on things late at night after my job. (lest I be promoted to customer)

**Comment by jsvigneshkanna** [comment]
No problem @Kabiirk take your time

Also check for other issue which are unassigned
