### ISSUE TITLE
[FEATURE]: Social media buttons in tailwindcss

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#49]
### Description

Need to create code for social+icon button as per below image.

- The final code should be placed under path `tailwind_components/buttons` with file name as solid_social_button1.jsx
- The file as to be imported to `tailwind_components/buttons/collection.js` file as per example and added to the buttonCollections list
- Post these process, go to components tab in website and check whether the codepen is updated

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196490318-a659f8d0-0249-4f21-9c0a-2d1d888cc4eb.png)

### Are you taking this fetaure implementaion

No

**Comment by Anuran12** [comment]
@jsvigneshkanna i would like to work on this.

**Comment by jsvigneshkanna** [comment]
Hi @Anuran12 ,
Assigning you this issue, please follow the folder structure for codepen works properly

Let me know if any issue faced. also check for buttons design too

**Comment by Anuran12** [comment]
> Hi @Anuran12 ,
> Assigning you this issue, please follow the folder structure for codepen works properly
> 
> Let me know if any issue faced. also check for buttons design too

@jsvigneshkanna  okay great. I will send pr tomorrow. 

Can I be assigned in more than one issues ?

**Comment by jsvigneshkanna** [comment]
yeah, max 3 issues at a time @Anuran12
