### ISSUE TITLE
PR Template

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#5]
**Description:**
As this is a new repository, we need PR GitHub template. The template should be new PRs and should have below mentioned input fields

**PR template Requirement:**

1. PR title should start with - [what_type_of_fix]< title>
2. Description of the Fix <Required>
3. Issue number in hastag <REQUIRED>
4. Screenshot of the Fix (desktop and mobile view) <REQUIRED>
5. checklist (tested in local dev, made the fix as per issue conversation, starred the rep 😜) <REQUIRED>

new file format - `.github/pull_request_template.md`

`Give the file name a proper standardised one`

Reference: https://github.com/stevemao/github-issue-templates

**PR Requirement:**
1. Please check the above requirements are met
2. Always create new branch on forked repo from master to avoid and error while merging the fix
7. Please Star this repo while forking as that would increase this repo's visibility

Cheers 🎉

**Comment by AmanPachori** [comment]
Hi @jsvigneshkanna, can you bit elaborate on it?

**Comment by jsvigneshkanna** [comment]
Hi @AmanPachori ,

This is for adding new PR template where when contributors raise PR, they have to fill some fields like 
1. title
2. Issue for which fix is done
3. screenshot of fix

Adding this template would standardize the PR structure when reviewers take them for review
For reference:
![image](https://user-images.githubusercontent.com/42484705/196020709-261782aa-2fc6-498c-8601-5759a941d5af.png)

https://github.com/YoshithaRathnayake/NEW-YOSHITHA-WEBSITE/blob/main/.github/pull_request_template.md

**Comment by AmanPachori** [comment]
@jsvigneshkanna I would like to work on this can you assign it to me

**Comment by jsvigneshkanna** [comment]
Welcome @AmanPachori ,

Please make sure all checklist are met, Assigning this issue to you name

cheers mate 🍻

**Comment by jsvigneshkanna** [comment]
Thanks @AmanPachori for contribution, please check for other issues too
