### ISSUE TITLE
[FEATURE]: new tailwindss buttons

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#51]
### If you have any button design which can be built in tailwindcss, create issue and start working on it

- The final code should be placed under path `tailwind_components/buttons` with file name as <button_name>_button1.jsx
- The file as to be imported to `tailwind_components/buttons/collection.js` file as per example and added to the buttonCollections list
- Post these process, go to components tab in website and check whether the codepen is updated

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

Add screenshot of your button design which you are building

### Are you taking this fetaure implementaion

No

**Comment by iamkennis** [comment]
I will like to work on this

**Comment by jsvigneshkanna** [comment]
@iamkennis ,

Look for issue where you can build the button component in tailwindcss, and comment there

**Comment by iamkennis** [comment]
okay

**Comment by bhautikposhiya** [comment]
i will work on this

**Comment by jsvigneshkanna** [comment]
@bhautikposhiya 
Check this figma for form/input fields and build components which you are comfortable on with tailwindcss

https://www.figma.com/file/0eqV7t3UKKM14UeqCSfOZb/Essential-UI---Figma-Ui-Kit-(Community)?node-id=688%3A1988

Check similar PRs for files to be modified

**Comment by jsvigneshkanna** [comment]
Yeah sure creating them

**Comment by iamkennis** [comment]
Please assign me to one you create once you are done

**Comment by jsvigneshkanna** [comment]
@iamkennis ,

I have raised many more issue/features request. please look on it
