### ISSUE TITLE
[FEATURE]: Apple store button tailwind

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#52]
### Need to create code for Apple store  button as per below image.

- The final code should be placed under path `tailwind_components/buttons` with file name as apple_store_button1.jsx
- The file as to be imported to `tailwind_components/buttons/collection.js` file as per example and added to the buttonCollections list
- Post these process, go to components tab in website and check whether the codepen is updated

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196495920-a7f5c556-592b-422c-bb12-7bf8c39e9542.png)

### Are you taking this fetaure implementaion

No

**Comment by AbhishekTiwari23** [comment]
I would like to contribute. Can you please assign this issue to me?

**Comment by RachitGarg-12** [comment]
@jsvigneshkanna can you assign me this issue

**Comment by jsvigneshkanna** [comment]
Sure @RachitGarg-12 

Also if you can do below company buttons, that would awesome

Figma https://www.figma.com/file/0eqV7t3UKKM14UeqCSfOZb/Essential-UI---Figma-Ui-Kit-(Community)?node-id=688%3A1988

**Comment by jsvigneshkanna** [comment]
Hi @RachitGarg-12 , any updates,
let me know if help needed

**Comment by jsvigneshkanna** [comment]
Hi @RachitGarg-12 , unassigning you from this issue as it was inactive for more than 3 days

**Comment by rakicodes** [comment]
@jsvigneshkanna can i get assign to this issue?

**Comment by jsvigneshkanna** [comment]
Welcome back @rakicodes , please go ahead

**Comment by rakicodes** [comment]
@jsvigneshkanna can you clarify what i am working on?

**Comment by jsvigneshkanna** [comment]
We need to add ui component same as screenshot which is styled only with tailwindcss
You can refer other store buttons in codebase and how they are imported to collections.js file
