### ISSUE TITLE
[Feature]: footer for website

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#53]
### Feature Title

Website footer

### Description

This website requires footer and it has to new component which should be imported in every pages

The footer should contain below things

1. Logo
2. Footer links to different pages
3. Copyright text
4. Privacy, terms of issue, contribute guide links

### Motivation

Footer is main component of cool project

### Issue Type

Frontend

### Are you taking this fetaure implementaion

No

**Comment by AbhishekTiwari23** [comment]
I would like to contribute. Can you please assign this issue to me?

**Comment by sahilarora02** [comment]
Hey , I want to contribute in this repo. Please assign this issue to me

**Comment by jsvigneshkanna** [comment]
Hi @sahilarora02 
Assigning you this issue, please follow the instructions and make the footer creative yet simple, we can enhance it in subsequent prs
For reference take look at this pages footer- 
https://codedamn.com/contact

**Comment by jsvigneshkanna** [comment]
Any problem @sahilarora02 ?

**Comment by Harikarthyk** [comment]
Hey, I would like to contribute to this repo. Please assign this issue to me

**Comment by jsvigneshkanna** [comment]
Sure @Harikarthyk ,

Also check for other issues too

**Comment by jsvigneshkanna** [comment]
Hi @Harikarthyk ,
let me know if any help needed on this issue!

**Comment by jsvigneshkanna** [comment]
@Harikarthyk ,
Closing this issue, as it was in-active for more than 3 days
