### ISSUE TITLE
[Feature]: contact us page

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#54]
### Feature Title

Contact us page creation

### Description

Need to build new contact us page for this repos website in nextjs and to be linked to navbar

Should have form with name,email and text area

Should also contain social media icons

Should be creative in styling and color scheme

### Motivation

Contact us page makes website cooler

### Issue Type

Frontend

### Screenshot of the feature if done ?

Nill

### Are you taking this fetaure implementaion

No

**Comment by AbhishekTiwari23** [comment]
I would like to contribute. Can you please assign this issue to me?

**Comment by jsvigneshkanna** [comment]
@AbhishekTiwari23 
Assigning you this issue, please follow the instructions and make the page as creative yet simple
We can enhance it in subsequent contribution

**Comment by AbhishekTiwari23** [comment]
Ya, there was an exam at my college, so can you please give me a few hours, so that I can do a PR.
Thanks.

**Comment by jsvigneshkanna** [comment]
No problem @AbhishekTiwari23 
I was just asking whether you stuck with an issue

**Comment by jsvigneshkanna** [comment]
Hi @AbhishekTiwari23 

Just a reminder, you have 3 issues un-solved, please try to close as when you get time

**Comment by anantnipunge** [comment]
Can you please assign this issue to me ? Willing to contribute in your project.

**Comment by jsvigneshkanna** [comment]
@anantnipunge sure, please make sure the background color is same ad homepage banner and styled in tailwindcss

**Comment by anantnipunge** [comment]
Ok working on it.

**Comment by Viren0602** [comment]
Hello sir, can you assign this issue to me?

**Comment by jsvigneshkanna** [comment]
Sure @Viren0602
