### ISSUE TITLE
[Bug]: nav logo not redirecting

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#55]
### Bug Title

Non redirecting logo

### Description of BUG

Logo in navbar should redirect to homepage on click

### Reporduction URL of bug

Homepage

### Bug Issue Type

Frontend

### Screenshot of the issue if in UI/ Document

Nill

### Are you taking this issue fix

No

**Comment by Ved142** [comment]
Hey @jsvigneshkanna i would like to work on it. Please assign it to me.

**Comment by jsvigneshkanna** [comment]
Thank you for checking @Ved142 
Assigning you this issue, please also look for other issues too for footer
