### ISSUE TITLE
[Feature]: User card with message button

### ISSUE THREAD

**Issue by saroshfarhan** [jsvigneshkanna/tailwind_ui_components#56]
### Feature Title

User card with message button

### Description

This will have card using tailwind css and will have a button for users to message

### Motivation

Just wanted to try out something with cards and buttons.

### Issue Type

Frontend

### Screenshot of the feature if done ?

Final PR will look like below
<img width="1434" alt="Screenshot 2022-10-18 at 11 06 24 PM" src="https://user-images.githubusercontent.com/12766730/196504060-397f23d5-64d5-41d3-9a1a-15263bcaf3bd.png">

@jsvigneshkanna let me know if this is fine for a PR.

### Are you taking this fetaure implementaion

Yes

**Comment by saroshfarhan** [comment]
@jsvigneshkanna Have created this would like to know your thoughts.

**Comment by saroshfarhan** [comment]
ok @jsvigneshkanna

**Comment by saroshfarhan** [comment]
@jsvigneshkanna raised PR https://github.com/jsvigneshkanna/tailwind_ui_components/pull/57

**Comment by jsvigneshkanna** [comment]
@saroshfarhan 
Merged your pr, you can check the production website

Also raise many PRs for buttons or different components wit different design if you know
