### ISSUE TITLE
[Feature]: hamburger navmenu in mobile view

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#60]
### Feature Title

Hamburger navmenu

### Description

Website need hamburger nav bar in mobile view 
The final design is open for creativity

### Motivation

Mobile view navbar doesnt look as cool as desktops

### Issue Type

Frontend

### Screenshot of the feature if done ?

Nill

### Are you taking this fetaure implementaion

No

**Comment by AbhishekTiwari23** [comment]
I would like to contribute. Can you please assign this issue to me?

**Comment by jsvigneshkanna** [comment]
Hi @AbhishekTiwari23 
Welcome to our community, also take a look for future issues and features too

**Comment by jsvigneshkanna** [comment]
Closing as done
