### ISSUE TITLE
[FEATURE]: Scroll button in tailwind

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#64]
### Need to create code for scroll button as per below image.

- The final code should be placed under path `tailwind_components/buttons` with file name as rounded_scroll_button.jsx
- The file as to be imported to `tailwind_components/buttons/collection.js` file as per example and added to the buttonCollections list
- Post these process, go to components tab in website and check whether the codepen is updated

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/63/files

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196600328-f57ce8cf-8ef5-4c28-86d9-6a80e748b993.png)

### Are you taking this fetaure implementaion

No

**Comment by ahmed-sudani** [comment]
I would like to work on this

**Comment by RachitGarg-12** [comment]
@jsvigneshkanna i would like to contribute to this.

**Comment by jsvigneshkanna** [comment]
Hi @ahmed-sudani 
Please go ahead, assigning you this issue

**Comment by jsvigneshkanna** [comment]
@RachitGarg-12 ,
Apologies but will assign you another button component design
Issue https://github.com/jsvigneshkanna/tailwind_ui_components/issues/52

**Comment by jsvigneshkanna** [comment]
@RachitGarg-12 
Can you comment over issue #52 
I will assign that to your name
