### ISSUE TITLE
[FEATURE]: Get started button in tailwind

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#65]
### Description

**Need to create code for Get started button as per below image.**

- The final code should be placed under path `tailwind_components/buttons` with file name as rounded_get_started_button.jsx
- The file as to be imported to `tailwind_components/buttons/collection.js` file as per example and added to the buttonCollections list
- Post these process, go to components tab in website and check whether the codepen is updated

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/63/files

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196600570-d1f77d3f-27d2-4df1-9ca8-f86245c55a81.png)

### Are you taking this fetaure implementaion

No

**Comment by hugekontrast** [comment]
Can I work on this one? 
* If yes, then at hover should the background illustration keep on moving to one direction, like towards right.

**Comment by jsvigneshkanna** [comment]
Hi @hugekontrast 
Please go ahead, the hover state can as what you explained. 

Also please take look at other button component requests too

**Comment by hugekontrast** [comment]
On it sir.

**Comment by jsvigneshkanna** [comment]
@hugekontrast ,

If you have ang button design that can be built using tailwind, please raise PRs for them too

Will check those

**Comment by hugekontrast** [comment]
Okay, so I tried it and need suggestions,
https://codepen.io/Ashuzon/pen/RwymzWP

**Comment by jsvigneshkanna** [comment]
Looks good @hugekontrast , you can remove "Ready to dive in?
Start your free trial today." text - (only button is enough) .  please raise a PR

Also look for `alerts components` raised in issue tab

**Comment by hugekontrast** [comment]
I've left only the button in there. And surely, I'll look into alert one.

**Comment by jsvigneshkanna** [comment]
@hugekontrast ,

check PR's comment- https://github.com/jsvigneshkanna/tailwind_ui_components/pull/94#issuecomment-1284249147
