### ISSUE TITLE
Hey can update the Readme File according to the new changes 

### ISSUE THREAD

**Issue by kuldeepmangla** [jsvigneshkanna/tailwind_ui_components#66]
@jsvigneshkanna

**Comment by jsvigneshkanna** [comment]
Hi @kuldeepmangla 

I am assigning you this issue, go ahead

Also please look at other feature requests too

**Comment by jsvigneshkanna** [comment]
Thanks @kuldeepmangla for your contribution,

Check out this figma whether you can recreate any components in tailwind and please raise an issue for that component

https://www.figma.com/file/0eqV7t3UKKM14UeqCSfOZb/Essential-UI---Figma-Ui-Kit-(Community)?node-id=688%3A1988
