### ISSUE TITLE
[FEATURE]: Amazon store button in tailwind

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#78]
### Need to create code for Google play store button as per below image.

- The final code should be placed under path `tailwind_components/store_buttons` with file name as amazon_store_button.jsx
- The file as to be imported to` tailwind_components/store_buttons/collection.js` file as per example and added to the buttonCollections list
- Post these process, go to components tab in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196702553-3be57ed0-aaf8-4b7d-ad0a-da6ec16aa208.png)

### Are you taking this fetaure implementaion

no

**Comment by iamkennis** [comment]
Assign this to me

**Comment by jsvigneshkanna** [comment]
@iamkennis  Sure
