### ISSUE TITLE
[FEATURE]: Window store button in tailwind

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#79]
### Need to create code for Window store button as per below image.

- The final code should be placed under path `tailwind_components/store_buttons` with file name as windows_store_button.jsx
- The file as to be imported to` tailwind_components/store_buttons/collection.js` file as per example and added to the buttonCollections list
- Post these process, go to components tab in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196702959-8bc05fa6-7efd-4e66-b51c-ceacc1979c7d.png)

### Are you taking this fetaure implementaion

no

**Comment by iamkennis** [comment]
Assign this to me too

**Comment by jsvigneshkanna** [comment]
@iamkennis Sure
Thanks
