### ISSUE TITLE
[FEATURE]: Search input form in tailwindcss

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#81]
### Need to create code for simple input form as per below image.

- The final code should be placed under path `tailwind_components/forms` with file name as `search_input_form.jsx`
- The file as to be imported to` tailwind_components/store_buttons/forms.js` file as per example and added to the buttonCollections list
- Post these process, go to components tab in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196705951-1f07741f-424c-4ce6-949e-87bc3a2b79f3.png)

### Are you taking this fetaure implementaion

no

**Comment by Anuran12** [comment]
@jsvigneshkanna  I would like to work on this

**Comment by jsvigneshkanna** [comment]
assigning to your name, please make sure new files added under `tailwind_components/forms` folder
