### ISSUE TITLE
[FEATURE]: Slider Input in tailwindcss

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#82]
### Need to create code for Slider range Input as per below image.

- The final code should be placed under path `tailwind_components/forms` with file name as `slider_input_form.jsx`
- The file as to be imported to` tailwind_components/store_buttons/forms.js` file as per example and added to the buttonCollections list
- Post these process, go to components tab in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196706425-43c6d687-ef6d-45cf-a003-d2d6305067da.png)

### Are you taking this fetaure implementaion

no

**Comment by Anuran12** [comment]
@jsvigneshkanna  I would like to work on this

**Comment by Hamdrive** [comment]
Hi @jsvigneshkanna could you please assign this issue to me, I'd like to work on this

**Comment by jsvigneshkanna** [comment]
@Hamdrive ,

Great insight, hashmarks are appreciated
Assigning to your name

**Comment by Hamdrive** [comment]
@jsvigneshkanna regarding the importing of the component, shouldn't it be imported into `tailwind_components/forms/collection.js` and not `tailwind_components/store_buttons/forms.js`?

Going by the example PR mentioned for the button, it has been done like that, and also the `form.js` file does not exist in `store_buttons`

**Comment by jsvigneshkanna** [comment]
@Hamdrive ,
good check, my mistake apology

It should be under forms `tailwind_components/forms/collection.js`
