### ISSUE TITLE
[FEATURE]: Report alert in tailwindcss

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#84]
### Description

**Need to create code for Report alert as per below image.**

- The final code should be placed under path `tailwind_components/alerts` with file name as `report_alert.jsx`
- The file as to be imported to `tailwind_components/alert/collection.js` file as per example and added to the `alertCollections` list
- The alert should close on clicking cross icon
- Post these process, go to components tab (components/alert) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196720079-230e83ac-e3ed-492b-95d6-e600e2d9dee5.png)

### Are you taking this fetaure implementaion

no

**Comment by raazseth** [comment]
I want to contribute to this project. Please assign me!

**Comment by jsvigneshkanna** [comment]
@raazseth , go ahead!

**Comment by raazseth** [comment]
Just made a new PR, Please check it

**Comment by raazseth** [comment]
Hey,

I have pushed the code of issue #84 not #87 but you have closed the issue of 87 instead of 84. Please update it!

**Comment by jsvigneshkanna** [comment]
Sorry my bad @raazseth ,
Sleepless night effect 🤪

**Comment by jsvigneshkanna** [comment]
Closing this issue as done thank you @raazseth
