### ISSUE TITLE
[FEATURE]: alarm alert in tailwind

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#86]
### Description

**Need to create code for alarm  alert as per below image.**

- The final code should be placed under path `tailwind_components/alerts` with file name as `alarm _alert.jsx`
- The file as to be imported to `tailwind_components/alert/collection.js` file as per example and added to the `alertCollections` list
- The alert should close on clicking cross icon
- Post these process, go to components tab (components/alert) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196848864-4c323ac0-2452-46e9-ba02-2194e52fd658.png)

### Are you taking this fetaure implementaion

no

**Comment by deepaksuthar40128** [comment]
Sir can you assign it to me 🙂

**Comment by jsvigneshkanna** [comment]
Hi @deepaksuthar40128 ,
Assigning issue to your name, please follow the folder structure

Also check for other alert components in issue tab

**Comment by jsvigneshkanna** [comment]
Closing as done
