### ISSUE TITLE
[FEATURE]: Not-allowed alert in tailwind

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#87]
### Description

**Need to create code for Not-allowed alert as per below image.**

- The final code should be placed under path `tailwind_components/alerts` with file name as `not_allowed_alert.jsx`
- The file as to be imported to `tailwind_components/alerts/collection.js` file as per example and added to the `alertCollections` list
- The alert should close on clicking cross icon
- Post these process, go to components tab (components/alert) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196720873-ece30f2c-9cd9-45ab-a5b4-c89d45038f62.png)

### Are you taking this fetaure implementaion

no

**Comment by raazseth** [comment]
Hey, I want to contribute to this project. Please assign me!

**Comment by jsvigneshkanna** [comment]
@raazseth , sure please go on

Also check for other alert components too!

**Comment by raazseth** [comment]
There is no hacktoberfest-accepted label, So I just need confirmation if this part of the code is Hacktoberfest or not.

**Comment by jsvigneshkanna** [comment]
@raazseth ,

Apologies, missed this isssue's labels. But your PR would be counted to hacktoberfest as this repo has `hacktoberfest` labels
![image](https://user-images.githubusercontent.com/42484705/197001121-d2a905fd-07db-46ec-8128-1791a6852f27.png)

**Comment by jsvigneshkanna** [comment]
@raazseth , reopened this issue, this will be counted towards hacktoberfest

**Comment by raazseth** [comment]
Made a new PR #135. Please check it!

**Comment by jsvigneshkanna** [comment]
Closing as done @raazseth 
Thank you for your valuable contributions

**Comment by jsvigneshkanna** [comment]
The
