### ISSUE TITLE
[FEATURE]: tick alert in tailwind

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#88]
### Description

**Need to create code for Report tickas per below image.**

- The final code should be placed under path `tailwind_components/alerts` with file name as `tick_alert.jsx`
- The file as to be imported to `tailwind_components/alerts/collection.js` file as per example and added to the `alertCollections` list
- The alert should close on clicking cross icon
- Post these process, go to components tab (components/alert) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196721133-3e54e21d-5576-46c9-9e0f-75c7432e61e7.png)

### Are you taking this fetaure implementaion

no

**Comment by GAURCODER** [comment]
@jsvigneshkanna plz assign this issue to me

**Comment by jsvigneshkanna** [comment]
Sure @GAURCODER ,

also check for other alerts components too

**Comment by tanisha-tech360** [comment]
Ya sure you can assign me this issue
