### ISSUE TITLE
[FEATURE]: choose file input in tailwind

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#89]
### Description

**Need to create code for choose file input as per below image.**

- The final code should be placed under path `tailwind_components/forms` with file name as `choose_file_input.jsx`
- The file as to be imported to `tailwind_components/forms/collection.js` file as per example and added to the `formCollections` list
- Oncling input box, should open the folder to select any file
- Post these process, go to components tab (components/forms) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196721742-111fadaa-d853-43ae-9591-1e633b538f1c.png)

### Are you taking this fetaure implementaion

no

**Comment by streetcodec** [comment]
I want to work on this, please assign ! @jsvigneshkanna

**Comment by jsvigneshkanna** [comment]
Sure @streetcodec 
Also check other forms components to be built in issue tab and comment which you are comfortable on

**Comment by jsvigneshkanna** [comment]
Hi @streetcodec ,
let me know if any help needed on this issue!

**Comment by streetcodec** [comment]
Thanks @jsvigneshkanna I have made a PR, please review it!
