### ISSUE TITLE
[FEATURE]: checkbox in tailwind

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#90]
### Description

**Need to create code for checkbox  as per below image.**

- The final code should be placed under path `tailwind_components/forms` with file name as `checkbox.jsx`
- The file as to be imported to `tailwind_components/forms/collection.js` file as per example and added to the `formCollections` list
- The checkbox should be responsive to user actions
- Post these process, go to components tab (components/forms) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196722408-bc6740d6-0cbb-49a1-bcbd-9c4e7a48e69e.png)

### Are you taking this fetaure implementaion

no

**Comment by Rancho2002** [comment]
assign it to me @jsvigneshkanna

**Comment by tanisha-tech360** [comment]
Hey can you assign me this issue?

**Comment by jsvigneshkanna** [comment]
Hey @tanisha-tech360 

This issue is already been assigned, apologies for that,

you can look for other issues, - https://github.com/jsvigneshkanna/tailwind_ui_components/issues/88

**Comment by jsvigneshkanna** [comment]
@tanisha-tech360 ,

can I assign you that issue - #88

**Comment by tanisha-tech360** [comment]
@jsvigneshkanna you can assign me this issue

**Comment by jsvigneshkanna** [comment]
Sure, @tanisha-tech360 ,
also check for other issues too

**Comment by Rancho2002** [comment]
Hi @jsvigneshkanna why you assign this someone else? i am doing it already

**Comment by jsvigneshkanna** [comment]
@Rancho2002 ,

You can raise pr for this issue, will check the code

You are still assigned this issue, I asked other assignee to look for other issues
