### ISSUE TITLE
[FEATURE]: Radion buttons in tailwind

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#91]
### Description

**Need to create code for radio button as per below image.**

- The final code should be placed under path `tailwind_components/forms` with file name as `radio_button.jsx`
- The file as to be imported to `tailwind_components/forms/collection.js` file as per example and added to the `formCollections` list
- The radio button should be responsive to user actions
- Post these process, go to components tab (components/forms) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196722800-35f590da-0364-4ae0-b497-fb289ba60afb.png)

### Are you taking this fetaure implementaion

no

**Comment by Matl3us** [comment]
Can you assign me to this?

**Comment by jsvigneshkanna** [comment]
Sure @Matl3us ,

Also look for other issues/ features too

**Comment by jsvigneshkanna** [comment]
Hi @Matl3us ,
let me know if any help needed on this issue!

**Comment by jsvigneshkanna** [comment]
@streetcodec ,
Can you check this issue?

**Comment by streetcodec** [comment]
Yes @jsvigneshkanna , Please assign this to me! Will be interested to work on it!

**Comment by jsvigneshkanna** [comment]
Great @streetcodec 

Also check pricing cards too as you can learn more from there

**Comment by streetcodec** [comment]
@jsvigneshkanna Yes! Checked and will do them one by one!

**Comment by streetcodec** [comment]
@jsvigneshkanna should my version contain 4 buttons? And should the checkbox be like the one in picture, hollow from insode rest blue, or filled completely on check?

**Comment by jsvigneshkanna** [comment]
Yes @streetcodec ,
We can have 2/3 radios and color palette should be same as screenshot

**Comment by streetcodec** [comment]
@jsvigneshkanna I have made the PR for this! Please Review and if any changes are to be done, please suggest!
