### ISSUE TITLE
[FEATURE]: toggle switch in tailwind

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#92]
### Description

**Need to create code for toggle switch  as per below image.**

- The final code should be placed under path `tailwind_components/forms` with file name as `toggle_switch.jsx`
- The file as to be imported to `tailwind_components/forms/collection.js` file as per example and added to the `formCollections` list
- The toggle switch should be responsive to user actions
- Post these process, go to components tab (components/forms) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

![image](https://user-images.githubusercontent.com/42484705/196723101-90236b24-bf15-466a-b7d1-4a862dcf53f7.png)

### Are you taking this fetaure implementaion

no

**Comment by HondaChan14** [comment]
Hello could I be assigned this?

**Comment by jsvigneshkanna** [comment]
Sure @HondaChan14 ,

Also please check alert component design in issue tabs

**Comment by jsvigneshkanna** [comment]
Hi @HondaChan14 ,
let me know if any help needed on this issue!

**Comment by jsvigneshkanna** [comment]
Hi @HondaChan14 , unassigning you from this issue as it was inactive for more than 3 days

**Comment by AFPedreros** [comment]
Hello @jsvigneshkanna can I give it a try?

**Comment by jsvigneshkanna** [comment]
Sure @AFPedreros , please go ahead
The creativity on color and size is upto you

**Comment by AFPedreros** [comment]
Thank you!
