### ISSUE TITLE
[Feature]: new favicon for website

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/tailwind_ui_components#93]
### Feature Title

new favicon

### Description

We need new favicon to be added for website, I have added the image below

### Motivation

Favicon makes product cooler

### Issue Type

Frontend

### Screenshot of the feature if done ?

![image](https://user-images.githubusercontent.com/42484705/196743307-30731425-06c4-491d-9693-c1ec04ff7f52.png)

### Are you taking this fetaure implementaion

No

**Comment by jsvigneshkanna** [comment]
Sure @RohitShah1706 

Also look at unassigned issue too

**Comment by jsvigneshkanna** [comment]
@RohitShah1706 , any problem?

**Comment by chibuike-19** [comment]
Can this be assigned to me?

**Comment by jsvigneshkanna** [comment]
Sure @chibuike-19 ,

Also check for other issues too!
